### ISSUE TITLE
Creating Template for Meeting Notes

### ISSUE THREAD

**Issue by Hakkush-07** [bounswe/bounswe2023group7#10]
The template that meeting notes should follow will be created.

Deadline: 07.03.2023

**Comment by elifkizilky** [comment]
I added some emojis to the headers and main parts in the template.

**Comment by Hakkush-07** [comment]
The template can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-Notes-Template-(Meeting-%23%3F-01.01.1970)).
