### ISSUE TITLE
Gamepage/Review Scenario

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2023group7#100]
### Issue Description

Scenario page for Gamepage/Review

### Deadline of the Issue

10.04.2023

### Reviewer

@omersafakbebek

### Deadline for the Review

10.04.2023 - 14.00

**Comment by SouthAscend** [comment]
I've added it to the [User Scenarios](https://github.com/bounswe/bounswe2023group7/wiki/User-Scenario---Game-Page-Review).

**Comment by omersafakbebek** [comment]
Review is completed. The task is done.
