### ISSUE TITLE
Forum Scenario

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#101]
### Issue Description

Scenario page for forum will be prepared.

### Deadline of the Issue

10.04.2023-Monday-13.00

### Reviewer

@elifkizilky 

### Deadline for the Review

10.04.2023-Monday-17.00

**Comment by omersafakbebek** [comment]
The prepared scenario can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/User-Scenario---Forum).

**Comment by elifkizilky** [comment]
The work is reviewed and the necessary parts which are persona, story, goals, preconditions, actions, acceptance criteria and mock-ups are filled. The issue can be closed.
