### ISSUE TITLE
Milestone Report - Evaluation of Deliverables

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#108]
### Issue Description

I will write about evaluation of the status of deliverables and its impact on our project plan.

### Tasks

Parts of the task:
- [x] Write the evaluation
- [ ] Add it to the milestone report

### Deadline of the Issue

10.04.2023 - Monday - 14.00

### Reviewer

@omersafakbebek  

### Deadline for the Review

10.04.2023 - Monday - 16.00

**Comment by mtkamiloglu** [comment]
I wrote the evaluation of deliverable part of the milestone report after the review it can be closed.

**Comment by omersafakbebek** [comment]
Review is completed. The task is done.
