### ISSUE TITLE
Invidual Report Draft

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#109]
### Issue Description

A draft will be prepared and shared with the team members for easy use and coherency.

### Tasks

Parts of the task:
- [x] Prepare the draft
- [x] Share it with team members

### Deadline of the Issue

09.04.2023 12:00

### Reviewer

@senaal 

### Deadline for the Review

09.04.2023 23:59

**Comment by elifkizilky** [comment]
The draft is prepared and added to the wiki side bar so that my teammates can see it. The work is [here](https://github.com/bounswe/bounswe2023group7/wiki/Invidual-Contribution-Report-Template).

**Comment by senaal** [comment]
The task is done.
