### ISSUE TITLE
Scenario - Group

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#111]
### Issue Description

As we talked in group meeting, scenarios is needed to prepare. I will create scenario for "group".

### Tasks

_No Response_

### Extra Comments

_No Response_

### Final Step

_No Response_

### Deadline of the Issue

10.04.2023 - Monday - 14:00

### Reviewer

@SouthAscend

### Deadline for the Review

10.04.2023 - Monday - 21:00

**Comment by frknlke** [comment]
I have created the [scenario](https://github.com/bounswe/bounswe2023group7/wiki/Scenario-%231:-Join-a-Group). Mockup parts will be added later. For now, review is needed.

**Comment by SouthAscend** [comment]
After Mockup parts added, there will be a revision issue on this topic.
