### ISSUE TITLE
Introduction of Requirements

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2023group7#115]
### Issue Description

I will do the intro part to the Requirements

### Deadline of the Issue

10.04.2023

### Reviewer

@elifkizilky 

### Deadline for the Review

10.04.2023

**Comment by elifkizilky** [comment]
Purpose, document convention, and product scope parts in the introduction are written according to the SRS model and can be accessed by this [link](https://github.com/bounswe/bounswe2023group7/wiki/Requirements). We didn't mention the references part since we did not use references.
