### ISSUE TITLE
Individual Report - Hakan Karakuş

### ISSUE THREAD

**Issue by Hakkush-07** [bounswe/bounswe2023group7#116]
### Issue Description

As discussed during meeting 7, I will create my individual report and fill RAM accordingly.

### Tasks

Parts of the task:
- [x] write individual report
- [x] fill RAM
- [x] add to wiki and milestone report

### Deadline of the Issue

10.04.2023 15.00

### Reviewer

@SouthAscend 

### Deadline for the Review

10.04.2023 23.59

**Comment by Hakkush-07** [comment]
My individual contribution report is done [here](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-(Hakan-Karaku%C5%9F)) and will soon be added to milestone report.

**Comment by SouthAscend** [comment]
I did not notice any errors in the report and it's accessible in the [Milestone Report](https://github.com/bounswe/bounswe2023group7/wiki/Milestone-1-Report).
