### ISSUE TITLE
Game Page Mock-up for Mobile

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#117]
### Issue Description

We should create game page mockups for mobile devices

### Tasks

Parts of the task:
- [x]  Analyzing the web mock up
- [x]  Creating mock up for mobile

### Deadline of the Issue

09.04.2023

### Reviewer

@senaal 

### Deadline for the Review

09.04.2023

**Comment by tuluyhansozen** [comment]
[Mock Up](https://www.figma.com/file/ys7rBkkB4wAThXJVYEscff/Design?node-id=0-1&t=UMRgokt9cnguwk5V-0)

**Comment by senaal** [comment]
The task is done.
