### ISSUE TITLE
Event Scenario

### ISSUE THREAD

**Issue by Hakkush-07** [bounswe/bounswe2023group7#118]
### Issue Description

A scenario for events will be created.

### Deadline of the Issue

10.04.2023 15.00

### Reviewer

@omersafakbebek 

### Deadline for the Review

10.04.2023 23.59

**Comment by Hakkush-07** [comment]
An example scenario for participating in an event is created [here](https://github.com/bounswe/bounswe2023group7/wiki/Scenario:-Participate-in-an-Event).

**Comment by omersafakbebek** [comment]
Review is completed. The task is done.
