### ISSUE TITLE
Individual Report - Fatma Sena Alçı

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#119]
### Issue Description

The individual report will be prepared.

### Tasks

Parts of the task:
- [x] Prepare individual report
- [x] Add it to the report and GitHub

### Deadline of the Issue

10.04.2023

### Reviewer

@yunusemrealtug 

### Deadline for the Review

10.04.2023

**Comment by senaal** [comment]
Individual contribution report is done and it needs review.

**Comment by yunusemrealtug** [comment]
There is nothing missed necessity, so I'm closing. However, I suggest you to explain and review your management related significant issues. It seems not required but I think it will be better for you.
