### ISSUE TITLE
Milestone Report - List and Status of Deliverables

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#125]
### Issue Description

I will prepare the part of the milestone report which includes list and status of deliverables.

### Deadline of the Issue

10.04.2023-Monday-19.00

### Reviewer

@frknlke 

### Deadline for the Review

10.04.2023-Monday-22.00

**Comment by omersafakbebek** [comment]
Table for list and status of deliverables has been added to the milestone report template.

**Comment by frknlke** [comment]
I reviewed the table. There is no error. I will close the issue.
