### ISSUE TITLE
Updating Mock-ups & Related Pages

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#127]
### Issue Description

The Mock-up pictures are updated and cropped. New pictures should be added to the Mock-up page and to the related user scenarios.

### Tasks

Parts of the task:
- [x] Add the Mockups to Mock-up main page
- [x] Update the mockups at user scenarios 

### Deadline of the Issue

10.04.2023 18.00

### Reviewer

@elifkizilky 

### Deadline for the Review

10.04.2023 20.00

**Comment by melihgezerr** [comment]
Mock-ups are updated and added more specific scenarios. You can find the pages  [here](https://github.com/bounswe/bounswe2023group7/wiki/User-Scenarios).

**Comment by elifkizilky** [comment]
I reviewed the page and the mockups are added to user scenarios accordingly. All user scenarios can be accessed by this [link](https://github.com/bounswe/bounswe2023group7/wiki/User-Scenarios).
