### ISSUE TITLE
Evolution Of Tools Figma

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#128]
### Issue Description

I will write the evolution of tools "Figma" part.

### Deadline of the Issue

10.04.2023

### Reviewer

@elifkizilky 

### Deadline for the Review

10.04.2023

**Comment by elifkizilky** [comment]
I checked the content from our shared folder and the work is completed. You can access our milestone report including this section from this [link](https://github.com/bounswe/bounswe2023group7/wiki/Milestone-1-Report).
