### ISSUE TITLE
Creating the NodeJS project for the practice app.

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#148]
### Issue Description

The NodeJS project for the practice app will be created and uploaded to GitHub repository.

### Tasks

Parts of the task:
- [x] Creating the NodeJS project
- [x] Uploading the project to the repository.

### Deadline of the Issue

01.05.2023-19.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

01.05.2023-23.59

**Comment by omersafakbebek** [comment]
The practice app with initialized with NodeJS. The work can be reviewed through [#149](https://github.com/bounswe/bounswe2023group7/pull/149) and merged.

**Comment by yunusemrealtug** [comment]
![image](https://user-images.githubusercontent.com/100098311/235777507-9e0f40a7-6781-4dff-8100-c20758fc4a31.png)
I ran the program and it works without no problem.
