### ISSUE TITLE
Templates,MeetingNotes SideBar&Contents

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#15]
Elif, Hakan and I have different duties.

- [x] Creating the personal page template. (Elif)
- [x] Creating the meeting notes template. (Hakan)
- [x] Creating the issue template. (Melih)
- [x] Editing the templates sidebar. (Melih)
- [x] Meeting notes side bar(Melih)

**Comment by elifkizilky** [comment]
Personal page template is added and can be seen on this [page](https://github.com/bounswe/bounswe2023group7/wiki/Personal-Page-Template). The corresponding issue is #4.

**Comment by melihgezerr** [comment]
I edited the sidebar and added an [issue template](https://github.com/bounswe/bounswe2023group7/blob/main/.github/ISSUE_TEMPLATE/task_issue.yaml).
