### ISSUE TITLE
Meeting Notes #9

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#150]
### Issue Description

I will create the meeting notes page and add meeting notes. 

### Tasks

Parts of the task:
- [x] I will create the meeting notes page
- [x] I will add the meeting notes to the this page

### Deadline of the Issue

07.05.2023 - Sunday - 20.00

### Reviewer

@elifkizilky 

### Deadline for the Review

07.05.2023 - Monday - 20.00

**Comment by mtkamiloglu** [comment]
I created the page and added the notes

**Comment by elifkizilky** [comment]
The work is reviewed and can be accessed by this [link](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%239-(04.05.2023)). The issue can be closed.
