### ISSUE TITLE
Create LocationSchema for API

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#161]
### Issue Description

I will create LocationSchema in MongoDB database in location.model.js file for my API which is described at #158 . This model will include the functions:

- getLocationHistory
- addLocation

This model will have the following indexes:
- email
- city
- region 
- postalCode 
-  country
- country flag 
- time

### Tasks

Parts of the task:
- [x] Define LocationSchema with corresponding indexes
- [x] Define corresponding functions

### Final Step

After I will complete my work, I will create a pull request for review.

### Deadline of the Issue

09.05.2023 23.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

10.05.2023 23:59

**Comment by elifkizilky** [comment]
The task is implemented and pull request is done. Issue needs review

**Comment by yunusemrealtug** [comment]
Yes, I reviewed in pull request and saw it works well. Code does not have problem as I review.
