### ISSUE TITLE
Unit Test for Location API

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#163]
### Issue Description

As for my API which is described at #158, I will create a unit test to make sure that the endpoints working as expected. For this purpose, I will use JEST which my teammate made the configuration earlier.

### Tasks

Parts of the task:
- [x] Create location.test file at tests folder

### Final Step

After I finish my task, I will create a pull request for review.

### Deadline of the Issue

09.05.2023 23.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

10.05.2023 23:59

**Comment by elifkizilky** [comment]
The task is implemented and pull request is done. Issue needs review

**Comment by yunusemrealtug** [comment]
The tests sufficient for the api. Closing.
