### ISSUE TITLE
Change in the Unit Test for Location API

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#187]
### Issue Description

User authorization is added to our project. Therefore, before the conduct of the test, an access token should be created for the user. I will create a access_token for the user with beforeAll, then delete the test user from database with afterAll. 

### Tasks

Parts of the task:
- [x] Change the test file
- [x] Push it to development branch

### Deadline of the Issue

11.05.2023 12:00

### Reviewer

@frknlke

### Deadline for the Review

12.05.2023 12:00

**Comment by elifkizilky** [comment]
The task is implemented and pull request is done. Issue needs review

**Comment by frknlke** [comment]
Task is completed, closing the issue.
