### ISSUE TITLE
Unit Test for Genre API

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#188]
### Issue Description

As for my API, I will create a unit test to make sure that the endpoints working as expected. For this purpose, I will use JEST which my teammate made the configuration earlier.

### Tasks

Parts of the task:
- [x] Creating unit test.

### Deadline of the Issue

11,05.2023

### Reviewer

@frknlke 

### Deadline for the Review

11.05.2023

**Comment by senaal** [comment]
The task is completed, the code is merged to the main. The issue needs review. @frknlke

**Comment by frknlke** [comment]
Task is completed, closing the issue.
