### ISSUE TITLE
Frontend of Platform App

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#189]
### Issue Description

As in I described in  https://github.com/bounswe/bounswe2023group7/issues/159, I am developing an app about game platforms. After the completing most part of the backend I am dealing the its interface.

### Deadline of the Issue

11.05.2023 - Thursday - 23.59

### Reviewer

@elifkizilky 

### Deadline for the Review

12.05.2023 - Thursday - 23.59

**Comment by yunusemrealtug** [comment]
I prepared frontend, and it can be reviewed.

**Comment by elifkizilky** [comment]
It is reviewed and can be seen on http://52.59.238.73:3000/. Issue can be closed.
