### ISSUE TITLE
Edit Issue Template 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#20]
### Issue Description

Adding reviewer and other deficiencies

### Tasks

Parts of the task:
- [ ] ...
- [ ] ...
- [ ] ...

### Deadline of the Issue

12.03.2023

**Comment by melihgezerr** [comment]
I edited the issue template added reviewer and final step secitons. You can see the new template [here](https://github.com/bounswe/bounswe2023group7/blob/main/.github/ISSUE_TEMPLATE/task_issue.yaml).
