### ISSUE TITLE
Milestone Report

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#200]
### Issue Description

We will write a report  prepared using markdown and including at least the following:

Executive Summary:
- Summary of project and overall status
- Description of the basic functionality of your project (can include screen shots) URL of practice app code and the tag
-- URL of your application that was deployed with docker
Any information we may need to test your application
Instructions for building the application with docker.
-- API URL (the URL should take us to a documented API)
- Links to meeting notes related to practice app
- Lessons learned: evaluation of tools and processes utilized to manage the team project. 
-- Challenges you met as a group

### Tasks

Parts of the task:
- [x] Create the page under deliverables
- [x] Add the necessary contents

### Deadline of the Issue

12.05.2023 22:00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

12.05.2023 23:59

**Comment by elifkizilky** [comment]
I added the header, and contributors also wrote the executive summary and evaluation of the processes part. You can access the page from [here](https://github.com/bounswe/bounswe2023group7/wiki/Milestone-2-Report).

**Comment by melihgezerr** [comment]
I wrote the evaluation of tools part.

**Comment by mtkamiloglu** [comment]
I wrote functionality of my API and add link to the my [individual report](https://github.com/bounswe/bounswe2023group7/wiki/Member-Contribution-Report-(Muhammet-Tayyip-Kamilo%C4%9Flu))

**Comment by elifkizilky** [comment]
I added table of contents.

**Comment by elifkizilky** [comment]
Everyone added their API functionalities, milestone report is completed on time. Issue can be reviewed and closed

**Comment by omersafakbebek** [comment]
I wrote the Instructions for building the application with docker, Any information that you may need to test our application parts of the milestone report and part about the urls of the practice app.

**Comment by senaal** [comment]
I added my individual report and API function functionality.

**Comment by mtkamiloglu** [comment]
[Milestone report](https://github.com/bounswe/bounswe2023group7/wiki/Milestone-2-Report) is completed and can be found in both release tags and wiki sidebar under the deliverables section. So, I am closing this issue.
