### ISSUE TITLE
Elif Kızılkaya Individual Contribution

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#201]
### Issue Description

For the milestone report, we will be writing individual reports which includes the following:
- Their own name (as section name)
- Links to important issues (git issues) and wiki documentation related to practice application
- The name, route, description of utilized third party URIs
- The name, route, description of the created API functions
- Description of unit tests. You can include code fragments to illustrate.
- Sample calls: Show a transcript of a request and response for the API functions you used and that you provide. The transcript should include the request and the detailed response (headers, status code, json etc.)
- Any other significant work related to this release (such as Docker, AWS, DB, Framework)
- Describe any challenges you met during implementation.

### Tasks

Parts of the task:
- [x] Create the page
- [x] Include the content

### Deadline of the Issue

12.05.2023 22:00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

12.05.2023 23:59

**Comment by yunusemrealtug** [comment]
One of the who does more than written. Well done. Thanks for the term. Closing.
