### ISSUE TITLE
Yunus Emre Altuğ Individual Report

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#204]
### Issue Description

I have to prepare a section summarizing my contributions. I will provide:
- Links to important issues (git issues) and wiki documentation related to practice application
- The name, route, description of utilized third party URIs
- The name, route, description of the created API functions
- Description of unit tests. You can include code fragments to illustrate.
- Sample calls: Show a transcript of a request and response for the API functions you used and that you provide. The transcript should include the request and the detailed response (headers, status code, json etc.)
- Any other significant work related to this release (such as Docker, AWS, DB, Framework)
- Describe any challenges you met during implementation.

### Deadline of the Issue

12.05.2023 - Friday - 22.59

### Reviewer

@omersafakbebek 

### Deadline for the Review

12.05.2023 - Friday - 23.59

**Comment by yunusemrealtug** [comment]
The report is ready. Can be reviewed.

**Comment by omersafakbebek** [comment]
I checked the individual contribution report. Good Work!
