### ISSUE TITLE
Ömer Şafak Bebek Individual Report

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#205]
### Issue Description

I have to prepare a section summarizing my contributions. I will provide:

* Links to important issues (git issues) and wiki documentation related to practice application
* The name, route, description of utilized third party URIs
* The name, route, description of the created API functions
* Description of unit tests that I created.
* Sample calls: Show a transcript of a request and response for the API functions you used and that you provide. The transcript should include the request and the detailed response (headers, status code, json etc.)
* Any other significant work related to this release (such as Docker, AWS, DB, Framework)
* Description of any challenges I met during implementation.

### Deadline of the Issue

12.05.2023 - Friday - 22.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

12.05.2023 - Friday - 23.59

**Comment by yunusemrealtug** [comment]
Only said frontend is hard, because backend is easy for him :). Well written report and well done project. Thanks for the term. Closing.
