### ISSUE TITLE
Creating a remote database for backend of the practice app.

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#217]
### Issue Description

Throughout the development process, we used local databases. For deployment, we will create a remote database by using mongodb atlas.

### Deadline of the Issue

12.05.2023 - Friday - 22.59

### Reviewer

@senaal 

### Deadline for the Review

12.05.2023 - Friday - 23.59

**Comment by mtkamiloglu** [comment]
We created a database whose host is an AWS Frankfurt server. We made this by using MongoDB Atlas. Our backend is connected to this database.
