### ISSUE TITLE
Explaining Streaming Games for Project Report

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#219]
### Issue Description

Explaining of API and functions of Streaming Games for Project Report

### Tasks

Parts of the task:
- [x] Explain Steaming Games for Project Report

### Deadline of the Issue

12.05.2023

### Reviewer

@frknlke 

### Deadline for the Review

12.05.2023

**Comment by tuluyhansozen** [comment]
@frknlke it is done

**Comment by frknlke** [comment]
Task is completed, closing the issue.
