### ISSUE TITLE
Editing Wiki Sidebar

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#22]
### Issue Description

We need to add meeting notes and templates links to sidebar in a dropdown list.

### Tasks

Parts of the task:
- [x] Create a dropdown list for meeting notes.
- [x] Create a dropdown list for templates.

### Deadline of the Issue

14.03.2023 - Tuesday - 23.59

### Reviewer

Furkan Ulke

### Deadline for the Review

14.03.2023 - Tuesday - 23.59

**Comment by mtkamiloglu** [comment]
I also created a dropdown list for researches.

**Comment by frknlke** [comment]
Dropdown lists for meeting notes and templates were added to the sidebar successfully. Review is completed and I am closing the issue.
