### ISSUE TITLE
Unit Test for Streaming Games API

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#220]
### Issue Description

I write Unit tests for Streaming Games API .

### Tasks

Parts of the task:
- [x] coding
- [x] testing

### Deadline of the Issue

12.05.2023

### Reviewer

@omersafakbebek 

### Deadline for the Review

12.05.2023

**Comment by tuluyhansozen** [comment]
@omersafakbebek it is done

**Comment by omersafakbebek** [comment]
I checked the unit tests. They passed successfully.
