### ISSUE TITLE
Game Model for Streaming Games 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#221]
### Issue Description

I will create GameSchema

### Tasks

Parts of the task:
- [x] create schema

### Deadline of the Issue

GameSchema

### Reviewer

@melihgezerr 

### Deadline for the Review

GameSchema

**Comment by tuluyhansozen** [comment]
@melihgezerr  it is done

**Comment by melihgezerr** [comment]
okay i am closing it.
