### ISSUE TITLE
Route file for Streaming Games

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#222]
### Issue Description

I will create route file

### Tasks

Parts of the task:
- [x] coding 

### Deadline of the Issue

12.05.2023

### Reviewer

@frknlke 

### Deadline for the Review

12.05.2023

**Comment by tuluyhansozen** [comment]
@frknlke it is done

**Comment by frknlke** [comment]
Branch merged with main, closing the issue.
