### ISSUE TITLE
Controller of Streaming Games

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#223]
### Issue Description

I will create controller file for Streaming Games

### Tasks

Parts of the task:
- [x] coding

### Deadline of the Issue

12.05.2023

### Reviewer

@yunusemrealtug 

### Deadline for the Review

12.05.2023

**Comment by tuluyhansozen** [comment]
@yunusemrealtug it is done

**Comment by yunusemrealtug** [comment]
Reviewed it. Closing. Thanks for the term.
