### ISSUE TITLE
Create README.md file for Server

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#225]
### Issue Description

I will create a README.md file and explain how to install and run the server.

### Deadline of the Issue

12.05.2023 23:00

### Reviewer

@senaal 

### Deadline for the Review

12.05.2023 23:59

**Comment by elifkizilky** [comment]
I created the README file and it can be seen [here](https://github.com/bounswe/bounswe2023group7/blob/main/practice-app/server/README.md). Issue needs review.

**Comment by senaal** [comment]
The task is done. I am closing the issue.
