### ISSUE TITLE
Creating README.md file in practice-app/server directory

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#226]
### Issue Description

Dependencies and pre-run processes for practice practice-app need to be described

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Extra Comments

_No Response_

### Final Step

_No Response

### Deadline of the Issue

12.05.2023 - 23:00

### Reviewer

@elifkizilky

### Deadline for the Review

12.05.2023 - 23:50

**Comment by elifkizilky** [comment]
It is done and can be seen [here](https://github.com/bounswe/bounswe2023group7/blob/main/practice-app/README.md).
