### ISSUE TITLE
Tuluyhan Sözen  Individual Contribution

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#229]
### Issue Description

For the milestone report, we will be writing individual reports

### Tasks

Parts of the task:
- [x] .

### Deadline of the Issue

12.05.2023

### Reviewer

@frknlke 

### Deadline for the Review

12.05.2023

**Comment by tuluyhansozen** [comment]
@frknlke it is done

**Comment by tuluyhansozen** [comment]
https://github.com/bounswe/bounswe2023group7/wiki/Member-Contribution-Report-Tuluyhan-S%C3%B6zen/

**Comment by frknlke** [comment]
Review is completed, closing the issue.
