### ISSUE TITLE
Adding Base Feature Requirements Section to Wiki Page

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#23]
### Issue Description

We need to add initial feature requirements according to the [project description](https://github.com/bounswe/bounswe2023group7/files/10950664/Project_Description.pdf) that is given to us.

### Tasks

Parts of the task:
- [x] Determine what is required according to the [project description](https://github.com/bounswe/bounswe2023group7/files/10950664/Project_Description.pdf) .
- [x] List requirements under the corresponding section in [Wiki Page](https://github.com/bounswe/bounswe2023group7/wiki) .

### Deadline of the Issue

14.03.2023 - Tuesday - 09.00

### Reviewer

Guney Yuksel

### Deadline for the Review

14.03.2023 - Tuesday - 11.00

**Comment by frknlke** [comment]
I have created [Base Requirement page](https://github.com/bounswe/bounswe2023group7/wiki/Base-Requirements) and added the first half of it. Issue will be reviewed after @senaal complete her part.

**Comment by senaal** [comment]
I finished second part, issue can be reviewed.

**Comment by SouthAscend** [comment]
Requirement page is added in the wiki pages list but requirements individually are not listed in the wiki's first page.
