### ISSUE TITLE
Team Preferences Survey

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#232]
### Issue Description

To collect what the group has done until now and what everyone prefers to do, I will create a survey. 

### Final Step

After collecting all the information, the groups can be adjusted regarding everyone's interest.

### Deadline of the Issue

09.10.2023 - Monday - 10:00

### Reviewer

@frknlke 

### Deadline for the Review

09.10.2023 - Monday - 23:59

**Comment by yunusemrealtug** [comment]
Prepared and the preferences are being taken. The issue can be reviewed.

**Comment by frknlke** [comment]
Survey is created and group members are distributed according to their preferences. sub-teams will be announced soon. Thus, I will close the issue.
