### ISSUE TITLE
Reorganizing the README.md file

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#236]
### Issue Description

I will reorganize the README.md file for the new semester. I will add the new team members to this file. If we can decide on the team name I can add it. Also after taking a group photo I will add it.

### Deadline of the Issue

9.10.2023 - Monday - 13.00

### Reviewer

@frknlke 

### Deadline for the Review

10.10.2023 - Tuesday - 13.00

**Comment by mtkamiloglu** [comment]
I added the new team members' names and Github pages. I can add group photo if we take and and team name if we decide on it until tuesday.

**Comment by mtkamiloglu** [comment]
README.md can be updated after deciding group name and taking group photo. Until then it is up-to-date. @frknlke can you review and close the issue.

**Comment by frknlke** [comment]
I reviewed README. I will closing the issue. When group photo is taken and the group name is decided, issue could be re-opened.
