### ISSUE TITLE
Putting template for lab reports into templates section

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#237]
### Issue Description

The lab report provided by the lab assistants should be put into the templates section in the wiki sidebar for easy access.

### Deadline of the Issue

10.10.2023 - 11.00

### Reviewer

@frknlke 

### Deadline for the Review

10.10.2023 - 13.00

**Comment by elifkizilky** [comment]
The template is added to the wiki side bar and wiki home page. A review is needed.

**Comment by frknlke** [comment]
I reviewed the [template](https://github.com/bounswe/bounswe2023group7/wiki/Weekly-Lab-Report-Template). It's all fine. I will close the issue.
