### ISSUE TITLE
Finding team name/website name

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#243]
### Issue Description

We can find ourselves a team name and also a website name which can be the same or different. We can discuss under this issue and find good candidates.

### Deadline of the Issue

10.10.2023 - 10.00

**Comment by yunusemrealtug** [comment]
game7, gaVen, SeMe, gamecon, plaven, reseplay.

**Comment by haticerk** [comment]
Ludos might be a nice name for the project.

**Comment by melihgezerr** [comment]
Ludos is selected as the group/project name. I am closing this issue.
