### ISSUE TITLE
Creation of Personal Wiki Page

### ISSUE THREAD

**Issue by tacettinburakeren** [bounswe/bounswe2023group7#245]
### Issue Description

Since I have joined the team as a new member, a new personal wiki page should be created.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

10.10.2023 - Tuesday - 1pm

### Reviewer

@elifkizilky 

### Deadline for the Review

10.10.2023 - Tuesday - 1pm

**Comment by elifkizilky** [comment]
The page is completed and can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Tacettin-Burak-Eren).
