### ISSUE TITLE
Frontend organization for communication and management

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#247]
### Issue Description

The related communication channels should be opened in Discord and WhatsApp. Related changes should be added to the communication channel.

### Tasks

Parts of the task:
- [x] Open Discord channel and WhatsApp group
- [x] Update the information to the communication channel

### Deadline of the Issue

17.10.2023 11:00

### Reviewer

@haticerk 

### Deadline for the Review

17.10.2023 13:00

**Comment by mtkamiloglu** [comment]
I opened the communication channels on WhatsApp and Discord. @haticerk updated the communication plan. Issue can be reviewed.

**Comment by haticerk** [comment]
Nice job, thank you!
