### ISSUE TITLE
Communication between Issue Reviewer & Issue Assignee

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#25]
### Issue Description

As we experienced last week, we need to inform the reviewer of the issue completion & progress. We can discuss how to proceed here. Please comment on this issue.

### Deadline of the Issue

21.03.2023

**Comment by elifkizilky** [comment]
I think the assignee can inform the reviewer via WhatsApp or we can create a channel on discord for this purpose.

**Comment by elifkizilky** [comment]
Yes, the notification came to me when you mentioned my username, I think we can do like this under the reviewer section in the issues.

**Comment by melihgezerr** [comment]
I updated the issue template for indicating the reviewer, you can see the new template [here](https://github.com/bounswe/bounswe2023group7/blob/main/.github/ISSUE_TEMPLATE/task_issue.yaml)
