### ISSUE TITLE
Project planning for the whole semester

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#250]
### Issue Description

We should make the project planning for the semester using Gantt Schart for learning, implementation, and design phases taking into account milestone 1, milestone 2, and final milestone dates. For that purpose, we organize a meeting.

### Tasks

Parts of the task:
- [x] Hold the meeting
- [x] Project planning
- [x] Updating Repo

### Deadline of the Issue

12.10.2023 21.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

12.10.2023 23:00

**Comment by elifkizilky** [comment]
We held a hybrid meeting today between 20.00-23.00. We opened a project and organized a roadmap for our project plan.
The participants:

- Hatice Erk (writer)
- Yunus Emre Altuğ (writer)
- Elif Kızılkaya (writer)
- Hakan Karakuş (writer)
- Sena Alçı
- Melih Gezer
- Burak Eren
- Ömer Şafak Bebek
- Furkan Ülke
- Kardelen Erdal

**Comment by yunusemrealtug** [comment]
This was a fine groupwork. It is sufficient for now. Closing.
