### ISSUE TITLE
Backend organization for communication and management

### ISSUE THREAD

**Issue by Hakkush-07** [bounswe/bounswe2023group7#251]
### Issue Description

Communication channels for the backend team should be created and the members should be notified.

### Tasks

Parts of the task:
- [x] Create Whatsapp group
- [x] Create Discord roles and channels

### Deadline of the Issue

17.10.2023

### Reviewer

@yunusemrealtug 

### Deadline for the Review

17.10.2023

**Comment by yunusemrealtug** [comment]
There is a whatsapp group created and discord channel are well done. Thanks.
