### ISSUE TITLE
Mobile organization for communication and management

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#252]
### Issue Description

A new channel should be created to be used for communication within the mobile team throughout the semester.

### Tasks

Parts of the task:
- [x] Creating Whatsapp group
- [x] Creating Discord channel

### Deadline of the Issue

17.10.2023 - Tuesday - 13.00

### Reviewer

@frknlke 

### Deadline for the Review

17.10.2023 - Tuesday - 17.00

**Comment by frknlke** [comment]
WhatsApp group created by @kardelenerdal

**Comment by frknlke** [comment]
Discord channel also created. Issue will be closed.
