### ISSUE TITLE
Wiki Project Plan & RAM Update

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#255]
### Issue Description

In our Wiki page, previous Cmpe 352 project plan is displayed. For this semester, we used GitHub's roadmap feature. Thus, the page should be organized accordingly.

### Tasks

Parts of the task:

- [x] Organize pages

### Deadline of the Issue

15.10.2023 21.00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

15.10.2023 23.59

**Comment by elifkizilky** [comment]
The pages are organized and added the headlines for Cmpe 352 and Cmpe 451 separately to differentiate our works. The issue can be reviewed. Links:

- [RAM](https://github.com/bounswe/bounswe2023group7/wiki/Responsibility-Assignment-Matrix-(RAM))
- [Project Plan](https://github.com/bounswe/bounswe2023group7/wiki/Project-Plan)

**Comment by mtkamiloglu** [comment]
RAM and Project Plan is updated. I am closing the issue. Thanks.
