### ISSUE TITLE
Use Case Diagram Revision

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#260]
### Issue Description

We need to revise the use case diagram within the feedback from the last semester. 

### Deadline of the Issue

24 October 2023 - Tuesday - 1pm

### Reviewer

@kardelenerdal

### Deadline for the Review

24 October 2023 - Tuesday - 3pm

**Comment by elifkizilky** [comment]
We held a meeting with @haticerk  and revised the use case diagram. We organized the previous use cases according to requirements and we colorized them according to themes. We added game and entity related use cases and revised previous ones according to feedback. Work can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Use-Case-Diagrams). The issue needs to be reviewed.

![Use case diagram (5)](https://github.com/bounswe/bounswe2023group7/assets/69367633/725577f9-df9e-48ed-a186-d6fa7c96e479)

**Comment by kardelenerdal** [comment]
I reviewed the use case diagram. Colorizing according to the themes is a cool idea, the diagram is much more readable. Game and entity related use cases are on both guest users and registered users which is compatible with our user requirements. Everything looks fine, issue can be closed.
