### ISSUE TITLE
Dockerization of backend environment

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#262]
### Issue Description

We will create dockerfile for our project. Also, a docker-compose file will be created in order to run the project container and the database container with one command.

### Tasks

Parts of the task:
- [x] Creating dockerfile for the project.
- [x] Creating docker-compose.yml file

### Deadline of the Issue

23.10.2023-23.59

### Reviewer

@tacettinburakeren 

### Deadline for the Review

24.10.2023-15.00

**Comment by melihgezerr** [comment]
we did this job in our previous meeting, you can close this issue @tacettinburakeren
