### ISSUE TITLE
Creating Responsibility Assignment Matrix

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#263]
### Issue Description

Creating RAM for new semester.

### Tasks

Parts of the task:
- [x]  Creating RAM
- [x] Filling according to project plan.

### Deadline of the Issue

24 October 2023 - Tuesday - 1pm

### Reviewer

@haticerk 

### Deadline for the Review

24 October 2023 - Tuesday - 7pm

**Comment by senaal** [comment]
I created a new RAM and added new group members. I filled first three weeks contributions. It will be continued with project plan. Also, it must be updated week by week. For now, it took 1 hour.

**Comment by senaal** [comment]
The task is done and needs review. It can be seen [here](https://github.com/bounswe/bounswe2023group7/wiki/Responsibility-Assignment-Matrix-(RAM)).
@haticerk

**Comment by haticerk** [comment]
Thank you for your effort! It looks nice.
