### ISSUE TITLE
Adding Game to Sequence Diagram

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#264]
### Issue Description

Adding game sequence diagram.

### Tasks

Parts of the task:
- [x] Create sequence diagram.

### Deadline of the Issue

24 October 2023 - Tuesday - 1pm

### Reviewer

@elifkizilky 

### Deadline for the Review

24 October 2023 - Tuesday - 7pm

**Comment by elifkizilky** [comment]
The game sequence diagram is completed and added to the [sequence diagram page](https://github.com/bounswe/bounswe2023group7/wiki/Sequence-Diagrams) by my teammate @senaal . The work is reviewed and the issue can be closed.
