### ISSUE TITLE
Updating Mockups by Adding Game Page and Entity Page

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#265]
### Issue Description

We will create mockups for Entity page which doesn't exist last semester, and make some updates on Game Profile Page mockups. 

### Tasks

Parts of the task:
- [x] Create a mockup for entity page.
- [x] Update Game Profile Page

### Deadline of the Issue

24.10.2023 - Tuesday - 12.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

24.10.2023 - Tuesday - 15.00

**Comment by haticerk** [comment]
I have created a new mock-up for the entity page and updated the game profile page according to the new requirements in the mobile side. They can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/Mock-Ups).

<img src="https://github.com/bounswe/bounswe2023group7/assets/74210334/e3b70586-8677-4b35-9876-0755efe90c44" alt="entity" width="200"/>
<img src="https://github.com/bounswe/bounswe2023group7/assets/74210334/f2b5d358-4ccf-4570-9cf7-a9d6d62d1bdf" alt="game profile" width="200"/>
<img src="https://github.com/bounswe/bounswe2023group7/assets/74210334/24ee5a91-08e6-4f3f-91fa-8c3c57521c08" alt="game explore" width="200"/>

**Comment by mtkamiloglu** [comment]
I have created a mock-up for the Entity Page and made big updates on game profile page for new added requirements. They can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/Mock-Ups).

**Comment by mtkamiloglu** [comment]
@yunusemrealtug review can be made.

**Comment by yunusemrealtug** [comment]
Well done, it seems it has sufficient represenration of what we think about, closing the issue.
