### ISSUE TITLE
Creating deployment environment in AWS for backend

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#266]
### Issue Description

We will create an ec2 instance on aws. Docker will be installed in the ec2 instance.

### Tasks

Parts of the task:
- [x] Creating an ec2 instance on aws
- [x] Installing docker in the instance

### Deadline of the Issue

23.10.2023-23.59

### Reviewer

@Hakkush-07

### Deadline for the Review

24.10.2023-15.00

**Comment by melihgezerr** [comment]
we did this job in our previous meeting so you can close this issue @Hakkush-07
