### ISSUE TITLE
Dockerization for mobile environment

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#269]
### Issue Description

We will decide on dockerization options for mobile environment. If it needs we will do dockerization for mobile part.

### Tasks

Parts of the task:
- [x] Deciding on dockerization options for mobile
- [x] Do dockerization if it results as necessary

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

23.10.2023 - Monday - 23:59

### Reviewer

@senaal

### Deadline for the Review

24.10.2023 - Tuesday - 16:00

**Comment by haticerk** [comment]
Since Android development involves the use of emulators, which may not be straightforward to containerize, the dockerization is not necessary for the mobile app.

**Comment by frknlke** [comment]
I agree with you. Issue could be closed after review.

**Comment by senaal** [comment]
The dockerization is cancelled because it is unnecessary for mobile.
