### ISSUE TITLE
Creating github actions pipeline for automatization of the deployment of the backend project

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#270]
### Issue Description

We will create a workflow file for github actions pipeline. The pipeline will deploy the files in the backend folder to the created ec2 instance ([#266](https://github.com/bounswe/bounswe2023group7/issues/266)). The docker container which is running in the instance will be restarted.

### Tasks

Parts of the task:
- [ ] Creating workflow file
- [ ] Testing the pipeline

### Deadline of the Issue

23.10.2023-23.59

### Reviewer

@melihgezerr 

### Deadline for the Review

24.10.2023-15.00

**Comment by melihgezerr** [comment]
I added Unit Tests and @omersafakbebek added deployment pipelines so this issue is done for now.
