### ISSUE TITLE
Mobile Page Structure Design

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#271]
### Issue Description

We will design page structure for mobile app as planned in [lab report.](https://github.com/bounswe/bounswe2023group7/blob/main/reports/lab_report_3.md)

### Tasks

Parts of the task:
- [x] Review Mock-ups to refresh knowledge in mobile design
- [x] Design page structure for mobile app

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

23.10.2023 - Monday - 23:59

### Reviewer

@elifkizilky

### Deadline for the Review

24.10.2023 - Tuesday - 16:00

**Comment by haticerk** [comment]
We met the weekend with @senaal, @frknlke and @kardelenerdal. We decided on the structure and implemented the home page according to this structure. The issue can be closed after the review.

**Comment by elifkizilky** [comment]
I reviewed the home page for mobile and it is nicely done and committed, thank you for your effort and time. The issue can be closed.
