### ISSUE TITLE
Creating Deployment Environment in AWS for Frontend

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#272]
### Issue Description

We need to establish a robust deployment environment in AWS for our front-end applications to ensure seamless and scalable hosting. This environment will enhance our deployment process, improve availability, and simplify the scaling of resources as our user base grows. 

### Tasks

Parts of the task:
- [x] -

### Deadline of the Issue

24.10.2023 - 11:00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

24.10.2023 - 13:00

**Comment by elifkizilky** [comment]
We held a meeting with @yunusemrealtug and we got help from @omersafakbebek  via Discord. We successfully deployed our front-end and it can be seen from the [link](http://51.20.170.143:3000/).

Thank you @omersafakbebek 😃

**Comment by yunusemrealtug** [comment]
Thanks @omersafakbebek.

**Comment by mtkamiloglu** [comment]
I am closing the issue. Well done @yunusemrealtug @elifkizilky
