### ISSUE TITLE
Creating GitHub Actions Pipeline for Automatization of the Deployment Frontend

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#273]
### Issue Description

We will create a workflow file for GitHub actions pipeline. This pipeline will deploy the files in the frontend folder to the created EC2 instance (https://github.com/bounswe/bounswe2023group7/issues/266). The Docker container which is running in the instance will be restarted.

### Tasks

Parts of the task:
- [x] Creating workflow file

### Deadline of the Issue

24.10.2023 - Tuesday - 12.00

### Reviewer

@omersafakbebek 

### Deadline for the Review

24.10.2023 - Tuesday - 15.00

**Comment by elifkizilky** [comment]
We implemented actions pipeline for the frontend. We created PR and it needs to be reviewed.

**Comment by yunusemrealtug** [comment]
We marked @omersafakbebek as reviewer of the pr. Therefore I assigned him for review.

**Comment by omersafakbebek** [comment]
The pipeline works as expected. Issue is completed.
