### ISSUE TITLE
Frontend Page Structure Design

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#277]
### Issue Description

We will design the page structure for our front end. A well-structured page is the foundation for a user-friendly and maintainable interface. In this task, we will focus on designing the layout, components, and overall architecture of our frontend pages.

### Tasks

Parts of the task:
- [x] .

### Deadline of the Issue

24.10.2023 - 11:00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

24.10.2023 - 13:00

**Comment by elifkizilky** [comment]
We met with my team mates @mtkamiloglu  and @yunusemrealtug, also @haticerk  joined us for coherency with mobile team. We designed our page structure/layout in Figma. I shared the link via email for the review.

**Comment by mtkamiloglu** [comment]
I am closing this issue as completed.
