### ISSUE TITLE
Designing Home Page for Frontend	

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#279]
### Issue Description

We will design a basic home page via benefiting from our Mock-ups that we prepared last year and we will implement home page of frontend using ReactJS.

### Tasks

Parts of the task:
- [x]  Discuss and decide on possible design choices for home page of frontend.
- [x]  Implement home page of frontend using ReactJS.

### Deadline of the Issue

24.10.2023 - Tuesday - 12.00

### Reviewer

@elifkizilky 

### Deadline for the Review

24.10.2023 - Tuesday - 15.00

**Comment by yunusemrealtug** [comment]
we have already done it as design, I opened a new issue as #316. Closing
