### ISSUE TITLE
Research About Similar Project/Website Documentation

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#28]
### Issue Description

We examined similar projects last week and talked about their properties and design while we are producing questions about requirements. This week, we decided to document them and extend them into more projects, thus it will help us to have those documents on our wiki page while we are making mock-ups-scenarios & validating the requirements in the long process. Thus, the decided team members will extend the research about similar projects and document their design and properties by examining the questions:
1) What do they like/dislike and why?
2) What are the features and design styles? 
2.2) Can we/why should we use them? 

### Tasks

Parts of the task:
- [x] Look for the similar projects/websites
- [x] Prepare a documentation
- [x] Add them on our wiki page under "Researches" tab

### Extra Comments

This is a description of the task, please open another issue by your research project topic by mentioning this issue.

### Deadline of the Issue

19.03.2023 - 23.59

### Reviewer

@melihgezerr

### Deadline for the Review

20.03.2023 - 23.59

**Comment by melihgezerr** [comment]
Elif this issue is closely related to the issue that you mentioned #33 . Should both issues can be closed together?

**Comment by elifkizilky** [comment]
Yes but this is a detailed description of the group task, #33  is my own subtask. Hakan will also do research too, once we are both done, this can be closed

**Comment by Hakkush-07** [comment]
My research can be accessed [here](https://github.com/bounswe/bounswe2023group7/wiki/IGN-and-GameFAQs)
The page is added to wiki sidebar.

**Comment by melihgezerr** [comment]
@Hakkush-07 can you also add it to the "researches page" itself? i am closing this issue thank you.
