### ISSUE TITLE
Creating database in Docker container

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#280]
### Issue Description

A service for the container which runs postgresql db will be added to the docker-compose file.

### Tasks

Parts of the task:
- [x] Adding the related service

### Deadline of the Issue

23.10.2023-23.59

### Reviewer

@Hakkush-07 

### Deadline for the Review

24.10.2023-15.00

**Comment by melihgezerr** [comment]
we did this in our previous meeting so you can close this issue @Hakkush-07
