### ISSUE TITLE
Creating user table in database

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#284]
### Issue Description

A user entity will be created.

### Tasks

Parts of the task:
- [x] Creating the user entity

### Deadline of the Issue

23.10.2023-23.59

### Reviewer

@melihgezerr 

### Deadline for the Review

24.10.2023-15.00

**Comment by melihgezerr** [comment]
finished this task and succesfully merged, i am closing this issue.
