### ISSUE TITLE
Folder Structure Design for backend

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#285]
### Issue Description

For this issue, we will create our codebase and create folder structure.

### Tasks

Parts of the task:
- [x] Setup the codebase for backend
- [x] Create folder structure

### Deadline of the Issue

23.10.2023-23.59

### Reviewer

@omersafakbebek 

### Deadline for the Review

24.10.2023-15.00

**Comment by melihgezerr** [comment]
We created a folder structure and finished the setup for the backend so I am closing this issue
