### ISSUE TITLE
Deciding on PR, branch and deployment convention

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#286]
### Issue Description

We need to decide on PR and branching conventions.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

24.10.2023

### Reviewer

@Hakkush-07 

### Deadline for the Review

24.10.2023

**Comment by melihgezerr** [comment]
We decided branch name convention as : 

| Branch Type (feature, bugfix, ...) | Team Code (BE, FE, MB) | Issue Number | Explanation |

Example: feature/BE-523-login-endpoint

and there should be one reviewer for each issue and 2 reviewers for each PR

**Comment by senaal** [comment]
@melihgezerr I think we should add these conventions to the wiki to avoid confusion in the future, what do you think?

**Comment by melihgezerr** [comment]
they were added in weekly report, yes you are right
