### ISSUE TITLE
Folder Structure Design for mobile

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#287]
### Issue Description

We will have a discussion on the folder structure and create the folders.

### Tasks

Parts of the task:
- [x] Deciding the folder structure
- [x] Creating folders

### Deadline of the Issue

24.10.2023 - Tuesday - 12.00

### Reviewer

@senaal 

### Deadline for the Review

24.10.2023 - Tuesday - 15.00

**Comment by kardelenerdal** [comment]
We created the folder "mobile" and initialized our flutter project inside it.

**Comment by senaal** [comment]
The task is completed. It can be seen [here](https://github.com/bounswe/bounswe2023group7/tree/main/ludos/mobile)
