### ISSUE TITLE
Providing our Communication Plan on Wiki Page

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#29]
### Issue Description

At our first meeting, we decided on our communication channels and created them. We decided to have them on our Wiki-Page to make our project process clearer and visible to the project owner in the long process.

### Tasks

Parts of the task:
- [x] Create a Communication Plan page
- [x] Add the page on our Wiki

### Deadline of the Issue

20.03.2023 - 23.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

21.03.2023 - 23.59

**Comment by elifkizilky** [comment]
The page is created and added the wiki side bar. The content is missing.

**Comment by tuluyhansozen** [comment]
The plan is created. Waiting for review @yunusemrealtug
