### ISSUE TITLE
Creating Empty Placeholders Pages for Mobile

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#292]
### Issue Description

I will create empty placeholder pages for mobile platform and I will connect them to buttons exist in the home page.

### Tasks

Parts of the task:
- [x] Create empty scaffolds for each possible page that can be reachable from home page
- [x] Add navigation mechanism to that pages when corresponding buttons pressed.

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

27.10.2023 - Friday - 23:59

### Reviewer

@kardelenerdal

### Deadline for the Review

28.10.2023 - Saturday - 13:59

**Comment by frknlke** [comment]
I created empty pages and tied them up to  buttons in home page. After merged other commits, I will also create a PR.

**Comment by kardelenerdal** [comment]
PR is created, reviewed and merged successfully. Issue can be closed. Thanks.
