### ISSUE TITLE
Designing and Implementing of Login Page

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#296]
### Issue Description

I will create a Login page for our platform. In this page I will take the username or email of the user and password. Then I will send request to the backend.

### Tasks

Parts of the task:
- [x] Design login page.
- [x] Implement the login page.

### Deadline of the Issue

31.10.2023 - Tuesday - 12.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

31.10.2023 - Tuesday - 15.00

**Comment by mtkamiloglu** [comment]
Since signup and login are very similar pages in context, I used the same design that used in signup page. Again main implementation is completed and I connected the page to the server. But I am not closing the issue because minor updates can be done.

**Comment by yunusemrealtug** [comment]
As we tried to work this component, there was no problem, may be some design issues may be talked in future but is is sufficent for now.
