### ISSUE TITLE
Designing and Implementing of Sign-Up Page

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#297]
### Issue Description

I will make desing of the sign-up page and implement it using ReactJS. 

### Tasks

Parts of the task:
- [x] Desing the sign-up page.
- [x] Implement the sign-up page.

### Deadline of the Issue

31.10.2023 - Tuesday - 12.00

### Reviewer

@elifkizilky 

### Deadline for the Review

31.10.2023 - Tuesday - 15.00

**Comment by mtkamiloglu** [comment]
I designed Sign up page but my design choices has changed while writing code. I connected page to the backend server. User can successfully login now. Minor cosmetic changes will be made.

**Comment by elifkizilky** [comment]
The signup page is tested and working perfectly.

- User signs up :white_check_mark:
- User logins with the data provided while signing up :white_check_mark:
- Asks for 8 characters length password :white_check_mark:
- Password matching is required :white_check_mark:
