### ISSUE TITLE
Create "Research" Page 

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#3]
We should do research about a GitHub repository or an API and document it. To do this, we should create a Wiki page named "Research" and list our findings below. Please tick if you completed it.

- [x] Melih Gezer
- [x] Yunus Emre Altuğ
- [x] Güney Yüksel
- [x] Fatma Sena Alçı
- [x] Furkan Ülke
- [x] Elif Kızılkaya
- [x] Marcel Namyslo
- [x] Mehmet Tuluyhan Sözen
- [x] Muhammet Tayyip Kamiloğlu
- [x] Ömer Şafak Bebek
- [x] Hakan Karakuş

Deadline: 07.03.2023

**Comment by frknlke** [comment]
I have added [Marcel's Research](https://github.com/bounswe/bounswe2023group7/wiki/Favorite-Repository-(Marcel)) to the [Research section](https://github.com/bounswe/bounswe2023group7/wiki/📝-Researches). I think he forgot to add it.

**Comment by elifkizilky** [comment]
Each team member has done the research and the pages can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/%F0%9F%93%9D-Researches).
