### ISSUE TITLE
Posting our Questions About Requirements on our Wiki Page

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#30]
### Issue Description

Last week, we start with our questions about our project and ask them to the customer. This week, we decided to categorize them and share them on our Wiki by extending the questions. 

### Tasks

Parts of the task:
- [x] Categorize the questions
- [x] Create a Wiki page for questions

### Deadline of the Issue

20.03.2023 - 23.59

### Reviewer

@t

### Deadline for the Review

21.03.2023 - 23.59

**Comment by elifkizilky** [comment]
The page is created and added to the wiki bar, content should be added once they are revised with @senaal .

**Comment by senaal** [comment]
I added some of our questions to the wiki page. We will discuss other questions with @elifkizilky .

**Comment by elifkizilky** [comment]
The questions are added. Our design questions  will be discussed on later PS's. The page can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Questions-For-Requirements).
