### ISSUE TITLE
Revision of Implementation of Mobil Sign-up Page

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#302]
### Issue Description

Changing colors and connecting endpoints.

### Tasks

Parts of the task:
- [x] Change style according to design
- [x] Connect it to backend

### Deadline of the Issue

31.10.2023

### Reviewer

@kardelenerdal 

### Deadline for the Review

31.10.2023

**Comment by kardelenerdal** [comment]
I reviewed the PR and merged successfully. Issue can be closed.
