### ISSUE TITLE
Revision of .gitignore in Mobil Folder

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#303]
### Issue Description

To eliminate unnecessary files in the mobile, The .gitignore should be updated.

### Deadline of the Issue

27 October 2023 - Friday - 5pm

### Reviewer

@frknlke 

### Deadline for the Review

27 October 2023 - Friday - 11pm

**Comment by kardelenerdal** [comment]
I reviewed and approved the related [PR](https://github.com/bounswe/bounswe2023group7/pull/324). It works correctly.

**Comment by frknlke** [comment]
Branch merged into development. Issue will be closed.
