### ISSUE TITLE
Personal Milestone Report

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#307]
### Issue Description

For the first milestone, one of the deliverables are individual contribution report. For this, we will create a template for easy use and everyone will create their report according to their efforts.

### Tasks

Parts of the task:
- [ ] Create an individual contribution report template
- [ ] Adding reports to milestone report

### Deadline of the Issue

03.11.2023 21.00

### Reviewer

@melihgezerr 

### Deadline for the Review

03.11.2023 23.00

**Comment by melihgezerr** [comment]
@frknlke @mtkamiloglu @Hakkush-07 your personal contribution issues are still open, i am waiting for your issues to close this isse.

**Comment by melihgezerr** [comment]
@yunusemrealtug can you review @Hakkush-07 issue?
