### ISSUE TITLE
Implementation of Mobil Forgot Password Page

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#312]
### Issue Description

I will implement forgot password page for mobile. I will also establish connection to the corresponding backend endpoint.

### Tasks

Parts of the task:
- [ ] Establish connection with backend endpoint
- [ ] Create forgot password page for mobile

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

30.10.2023 - Monday - 23:59

### Reviewer

@kardelenerdal

### Deadline for the Review

31.10.2023 - Tuesday - 11:59

**Comment by kardelenerdal** [comment]
Forgot password pages are implemented in mobile application frontend. The related pr is reviewed and merged.
