### ISSUE TITLE
Revision of Implementation of Mobil Login Page

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#314]
### Issue Description

I will review our login page implementation. The design is decided by both mobile and frontend teams. Also, some requirements are updated. So, I will change our page according to the final decision.

### Tasks

Parts of the task:
- Colors will be updated.
- Components will be updated according to requirements.

### Final Step

After finishing the task, I will check if our mobile application works on an android device correctly.

### Deadline of the Issue

31.10.2023 - Tuesday - 08.00

### Reviewer

@frknlke 

### Deadline for the Review

31.10.2023 - Tuesday - 11.00

**Comment by kardelenerdal** [comment]
The related [PR](https://github.com/bounswe/bounswe2023group7/tree/feature/MB/314/revision_login_page).

**Comment by frknlke** [comment]
Mobil login page implemented and connected to corresponding endpoints. All changes merged into development. Closing the issue.
