### ISSUE TITLE
Implementation of Mobil Loading Spinner

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#315]
### Issue Description

I will add splash screen into our flutter mobile application.

### Deadline of the Issue

31.10.2023 - Tuesday - 08.00

### Reviewer

@senaal 

### Deadline for the Review

31.10.2023 - Tuesday - 11.00

**Comment by kardelenerdal** [comment]
The related PR can be found [here](https://github.com/bounswe/bounswe2023group7/pull/325).

**Comment by senaal** [comment]
The PR is successfully merged, thus I am closing the issue.
