### ISSUE TITLE
Creating Forgot Password Endpoints

### ISSUE THREAD

**Issue by Hakkush-07** [bounswe/bounswe2023group7#319]
### Issue Description

Endpoints for forgetting password should be created.

### Tasks

Parts of the task:
- [ ] forgotPassword endpoint
- [ ] updateUserPassword endpoint

### Deadline of the Issue

30.10.2023

### Reviewer

@melihgezerr

### Deadline for the Review

30.10.2023

**Comment by omersafakbebek** [comment]
This issue is handled with [#364](https://github.com/bounswe/bounswe2023group7/pull/364). So, I am closing this issue.
