### ISSUE TITLE
Draft for SRS Requirements Page

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#32]
### Issue Description

As mentioned in #31, we need a draft for the requirements. The guideline is shared on our moodle course page. A page on Wiki 
should be created by following the slide.

### Deadline of the Issue

19.03.2023 - 23.59

### Reviewer

@elifkizilky 

### Deadline for the Review

20.03.2023 - 23.59

**Comment by yunusemrealtug** [comment]
I opened a requirement page which is draft yet. Page lacks some important features.

**Comment by elifkizilky** [comment]
The requirement page made according to the draft and can be seen [here](https://github.com/bounswe/bounswe2023group7/wiki/Requirements).
