### ISSUE TITLE
Research About JoyFreak 

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#33]
### Issue Description

As mentioned in #28, I'm going to document the website [JoyFreak ](https://www.joyfreak.com/)according to the description.

### Deadline of the Issue

19.03.2023 - 23.59

### Reviewer

@senaal 

### Deadline for the Review

20.03.2023 - 23.59

**Comment by elifkizilky** [comment]
The page is created and the research is done, you can access the page from [here](https://github.com/bounswe/bounswe2023group7/wiki/JoyFreak). The page should be added to Wiki Sidebar once it is organized.

**Comment by elifkizilky** [comment]
The work needs review @senaal

**Comment by elifkizilky** [comment]
The page is added to the wiki side bar.

**Comment by senaal** [comment]
Review is completed and I am closing the issue.
