### ISSUE TITLE
Revision of README.md

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#338]
### Issue Description

The README.md on the home page should be updated. 

### Deadline of the Issue

31.10.2023 - Tuesday - 1pm

### Reviewer

@elifkizilky

### Deadline for the Review

31.10.2023 - Tuesday - 3pm

**Comment by haticerk** [comment]
I updated the README.md and created a [pull request](https://github.com/bounswe/bounswe2023group7/pull/339).

**Comment by elifkizilky** [comment]
The PR is reviewed and merged by @mtkamiloglu. The issue can be closed.
