### ISSUE TITLE
Meeting 3 Notes

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#35]
### Issue Description

Taking notes and uploading them to our wiki page.

### Tasks

Parts of the task:
- [x] Taking notes at meeting
- [x] Uploading the meeting notes properly 

### Deadline of the Issue

19.03.2023

### Reviewer

@Hakkush-07 

### Deadline for the Review

20.03.2023

**Comment by Hakkush-07** [comment]
[Meeting 3 notes](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%233-(17.03.2023))
