### ISSUE TITLE
Implementing the Log Out functionality

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#350]
### Issue Description

I will implement the log out function. I will simply remove the acces token from local storage.

### Tasks

Parts of the task:
- [x] Implement the log out function

### Deadline of the Issue

30.10.2023 - Monday - 23.59

### Reviewer

@elifkizilky 

### Deadline for the Review

31.10.2023 - Tuesday - 12.00

**Comment by elifkizilky** [comment]
The logout functionality is implemented and it is tested and working. The related PR is merged as well, the issue can be closed. Thank you for your time.
