### ISSUE TITLE
Sidebar in Home Page of Mobile

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#356]
### Issue Description

We need a sidebar with login/out and username functionalities.

### Deadline of the Issue

03.11.2023 - Friday - 12.00

### Reviewer

@haticerk 

### Deadline for the Review

03.11.2023 - Friday - 17.00

**Comment by haticerk** [comment]
The task is done. I also reviewed the PR, everything works correctly. Well done!
