### ISSUE TITLE
Fixing the rerendering bug

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#362]
### Issue Description

When I click the submit on login it rerenders all page. I will fix that bug.

### Deadline of the Issue

31.10.2023 - Tuesday - 12.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

31.10.2023 - Tuesday - 15.00

**Comment by yunusemrealtug** [comment]
OK, as we examined, it seems solved.
