### ISSUE TITLE
Meeting Notes of Milestone 1 Deliverables

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#375]
### Issue Description

We need to share tasks to prepare our Milestone 1 Deliverables.

### Deadline of the Issue

07.11.2023 - Tuesday - 13.00

### Reviewer

@elifkizilky 

### Deadline for the Review

07.11.2023 - Tuesday - 17.00

**Comment by kardelenerdal** [comment]
You can find the meeting notes [here](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%235-01.11.2023).

**Comment by elifkizilky** [comment]
The work is completed and the corresponding link for it is shared. The issue can be closed. Thank you for your time
