### ISSUE TITLE
Milestone Report Template and Link

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#377]
### Issue Description

For collaboration within our software development project, I'm going to create a milestone report template. This template will serve as a structured format for documenting project progress, achievements, and goals. I will share this template with all team members, inviting contributions to ensure a comprehensive and coherent report for our upcoming milestone.

### Tasks

Parts of the task:
- [x] Create a template
- [x] Share the link

### Deadline of the Issue

02.11.23 12.00

### Reviewer

@senaal 

### Deadline for the Review

02.11.23 18.00

**Comment by elifkizilky** [comment]
I created the milestone template and shared it with our group. The issue needs to be reviewed.

**Comment by senaal** [comment]
The issue is completed successfully. Thank you for effort.
