### ISSUE TITLE
Updating RAM for Personal Contributions - Elif Kızılkaya

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#378]
### Issue Description

To deliver at the milestone report 1, I'm going to update RAM for my contributions and reviews. 

### Tasks

Parts of the task:
- [x] Update RAM

### Deadline of the Issue

03.11.23 12.00

### Reviewer

@senaal  

### Deadline for the Review

03.11.2023 15.00

**Comment by elifkizilky** [comment]
I updated the RAM for my contributions. Also, I reviewed some of the assignments because of the minor changes in our project plan. The RAM can be accessed by this [link](https://github.com/bounswe/bounswe2023group7/wiki/Responsibility-Assignment-Matrix-(RAM)). The issue needs to be reviewed.

**Comment by senaal** [comment]
Rewiew is completed.
