### ISSUE TITLE
Evaluation of tools and processes - Mobile

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#379]
### Issue Description

For the mobile team, I will evaluate the tools we used and our overall processes for the Milestone 1 Deliverables for issue #308. 

### Deadline of the Issue

03.11.2023 - Friday - 12.00

### Reviewer

@haticerk 

### Deadline for the Review

03.11.2023 - Friday - 16.00

**Comment by haticerk** [comment]
I read your part in the milestone report. Well done!
