### ISSUE TITLE
Research About Geotagging

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#38]
### Issue Description

I will do research on what geotagging is, what it is used for, and how we can use it in our own project.

### Deadline of the Issue

20.03.2023 - Monday - 23.59

### Reviewer

@tuluyhansozen

### Deadline for the Review

20.03.2023 - Monday - 23.59

**Comment by mtkamiloglu** [comment]
Page is added: https://github.com/bounswe/bounswe2023group7/wiki/Geotagging, it needs review.

**Comment by mtkamiloglu** [comment]
I also added the page to the sidebar and the main page of the researches.

**Comment by tuluyhansozen** [comment]
I reviewed it and closed.
