### ISSUE TITLE
Individual Contribution Report Template Update

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#382]
### Issue Description

We have already an [individual contribution report](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-Template) on our wiki. However, there are minor changes that are asked for this milestone. I'm going to update it.

### Tasks

Parts of the task:
- [x] Update the individual contribution report template

### Deadline of the Issue

01.11.23 23.59

### Reviewer

@frknlke 

### Deadline for the Review

02.11.23 18.00

**Comment by elifkizilky** [comment]
I updated the individual contribution template and you can access it from this [link](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-Template). The issue needs to be reviewed.

**Comment by frknlke** [comment]
Template looks fine. Some of team members have already used it. Good work. Issue will be closed.
