### ISSUE TITLE
Summary of the Customer Feedback and Reflections Part

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#384]
### Issue Description

As indicated at #308,  we prepare for Milestone Report 1. It is essential to capture and summarize the valuable insights provided by our customers. Thus, I'm going to write a summary of the customer feedback and reflections. 

### Tasks

Parts of the task:
- [x] Write a summary of the customer feedback and reflections

### Deadline of the Issue

02.11.23 23.59

### Reviewer

@omersafakbebek 

### Deadline for the Review

03.11.2023 15.00

**Comment by elifkizilky** [comment]
I wrote the summary of the customer feedback and reflections part in the milestone report and it can be seen on the link shared in the team group. The issue needs to be reviewed.

**Comment by safakbebek** [comment]
I checked the related part of the report. The issue is completed now.

**Comment by omersafakbebek** [comment]
I checked the related part of the report. The issue is completed now.
