### ISSUE TITLE
Individiual Contribution Report For Milestone 1 - Ömer Şafak Bebek

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#385]
### Issue Description

I will create my personal contribution report to milestone 1 as mentioned in [#307](https://github.com/bounswe/bounswe2023group7/issues/307).

### Tasks

Parts of the task:
- [x] Creating the report
- [x] Adding the individual report to the milestone report.

### Deadline of the Issue

03.11.2023

### Reviewer

@yunusemrealtug 

### Deadline for the Review

03.11.2023

**Comment by omersafakbebek** [comment]
The work can be reviewed @yunusemrealtug .

**Comment by yunusemrealtug** [comment]
Reviewed. No mistakes are seen. Maybe you can group issues as i did :)
