### ISSUE TITLE
Individual Contribution Report - Kardelen Erdal

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#386]
### Issue Description

I will explain my contributions in the individual contribution part of Milestone 1 Deliverable, as in #307.   

### Tasks

Parts of the task:
- [x] Writing individual contribution report for myself.

### Deadline of the Issue

03.11.2023 - Friday - 12.00

### Reviewer

@frknlke 

### Deadline for the Review

03.11.2023 - Friday - 15.00

**Comment by kardelenerdal** [comment]
You can find my page [here.](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-(Kardelen-Erdal))

**Comment by frknlke** [comment]
Result looks fine. Issue will be closed.
