### ISSUE TITLE
Write the evaluation of the status of deliverables and its impact

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#389]
### Issue Description

I will write the evaluation of the status of deliverables and its impact for #308 

### Tasks

Parts of the task:
- [x] ...(1)
- [x] ...(2)
- [x] ...(3)

### Deadline of the Issue

3.11.2023 15:00

### Reviewer

@elifkizilky 

### Deadline for the Review

3.11.2023 17:00

**Comment by melihgezerr** [comment]
it is done you can review now @elifkizilky

**Comment by elifkizilky** [comment]
I reviewed the work and it is perfectly written. It is in the hackmd project right now. We will be sharing it in our repo once everyone fills their part. Thank you for your time.
