### ISSUE TITLE
Individual Contribution Report - Melih Gezer

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#390]
### Issue Description

As indicated in https://github.com/bounswe/bounswe2023group7/issues/307, for the milestone report, I'm going to write an individual contribution report about my contribution according to the template and add it to the milestone report.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

3.11.2023 15:00

### Reviewer

@senaal 

### Deadline for the Review

3.11.2023 17:00

**Comment by melihgezerr** [comment]
You can review now @senaal

**Comment by senaal** [comment]
It looks great, additionally I underlined your name. Thank you for your effort.
