### ISSUE TITLE
Evaluation of Tools and Processes - Frontend

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#392]
### Issue Description

For the frontend team, I will evaluate the tools we used and our overall processes for the Milestone 1 Deliverables. 

### Deadline of the Issue

03.11.2023 - Friday - 12.00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

03.11.2023 - Friday - 16.00

**Comment by yunusemrealtug** [comment]
I added the relevant fieldsi would you check it @mtkamiloglu

**Comment by mtkamiloglu** [comment]
I reviewed the part of report that you wrote. It is well written. Thank you!
