### ISSUE TITLE
Requirement Revision for Milestone 1 Report

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#393]
### Issue Description

As part of our ongoing software development project, we have already listed our requirements for the project. I am assigned to check before them for our project and milestone 1.

### Deadline of the Issue

03.11.2023 - Friday - 12.00

### Reviewer

@kardelenerdal 

### Deadline for the Review

03.11.2023 - Friday - 16.00

**Comment by yunusemrealtug** [comment]
Small revisions are made, if anything seems problematic please warn me @kardelenerdal

**Comment by kardelenerdal** [comment]
I reviewed your changes. Minor changes looks okay.  Thanks for adding "the average completion duration of the game" requirement. The issue can be closed.
