### ISSUE TITLE
Individual Contribution Report - Yunus Emre Altuğ

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#394]
### Issue Description

As indicated in https://github.com/bounswe/bounswe2023group7/issues/307, for the milestone report, I'm going to write an individual contribution report about my contribution according to the template and add it to the milestone report.

### Deadline of the Issue

03.11.2023 - Friday - 13:00

### Reviewer

@omersafakbebek 

### Deadline for the Review

03.11.2023 - Friday - 16:00

**Comment by yunusemrealtug** [comment]
It seems OK, @omersafakbebek would you check it.

**Comment by omersafakbebek** [comment]
I checked the report. The task is completed.
