### ISSUE TITLE
Revision of Mockups and Scenarios

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#397]
### Issue Description

Before developing the frontend of our project, we have created mockups and scenarios. I will make revision of project mockups and user scenarios. This task is essential for ensuring that our visual design and user experience align with the latest project requirements and user feedback. 

### Tasks

Parts of the task:
- [x] Revise User Scenarios
- [x] Revise Mockups

### Deadline of the Issue

02.11.23 - Thursday - 23.59

### Reviewer

@melihgezerr 

### Deadline for the Review

03.11.23 - Friday - 15.00

**Comment by mtkamiloglu** [comment]
I revised the signup page and reviewed other mockups as well. I will look for the scenarios.

**Comment by frknlke** [comment]
I examined the user scenarios and mock-ups before delivering them. I focused on the mock-ups and scenarios of the game feature that we added after the feedback. Both the past designs and the ones added this year seem to be correct.

**Comment by melihgezerr** [comment]
okay i am closing this issue if everyone is done.
