### ISSUE TITLE
Mock-Up Design Tool Selection

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#40]
### Issue Description

We need to decide on a tool that we will be using for our Mock-Ups. I found a blog that covers the tools on the Internet, here is the [link](https://www.browserstack.com/guide/top-website-mockup-tools). Please check them and share your idea.
It is better if it is free, simple, and easy to use.

### Deadline of the Issue

20.03.2023 - 23.59

**Comment by melihgezerr** [comment]
[Figma](https://www.figma.com/wireframe-tool/) is free mockup/wireframe tool, i think it is good. It has 4.5/5 user experience and suggested byt many websites.

**Comment by melihgezerr** [comment]
We decided to select Figma as stated above. So we create our mockups via [Figma](https://www.figma.com/wireframe-tool/).
