### ISSUE TITLE
Individual Contribution Report - Hakan Karakuş

### ISSUE THREAD

**Issue by Hakkush-07** [bounswe/bounswe2023group7#401]
### Issue Description

As indicated in #307, for the milestone report, I'm going to write an individual contribution report about my contribution according to the template and add it to the milestone report.

### Tasks

Parts of the task:
- [x] ...(1)
- [x] ...(2)
- [x] ...(3)

### Deadline of the Issue

03.11.2023 - 12.00

### Reviewer

@yunusemrealtug

### Deadline for the Review

03.11.2023 - 18.00

**Comment by Hakkush-07** [comment]
I have added my section to the report.

**Comment by yunusemrealtug** [comment]
OK, closing.
