### ISSUE TITLE
General Link for Updating RAM

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#403]
### Issue Description

 We are using markdown for RAM. For collaborative editing, we can use hackmd for RAM. I will share a link for this.

### Tasks

Parts of the task:
- [x] Create a project and share the link for hackmd

### Deadline of the Issue

03.11.2023 12.00

### Reviewer

@kardelenerdal 

### Deadline for the Review

03.11.2023 15.00

**Comment by kardelenerdal** [comment]
The project is created and the hackmd link is shared by @elifkizilky with the team.
