### ISSUE TITLE
Updating RAM with Personal Contributions

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#404]
### Issue Description

To meet Milestone 1's necessities I will update the RAM with my personal contributions.

### Tasks

Parts of the task:
- [x] Update the RAM

### Deadline of the Issue

03.11.2023 - Friday - 15:00

### Reviewer

@omersafakbebek 

### Deadline for the Review

03.11.2023 - Friday - 16:00

**Comment by mtkamiloglu** [comment]
I added my tasks to the RAM, and added reviewers of my tasks also. Issue can be reviewed @omersafakbebek .

**Comment by omersafakbebek** [comment]
Issue has been reviewed. The work is done.
