### ISSUE TITLE
Revising the ps&customer meetings

### ISSUE THREAD

**Issue by tacettinburakeren** [bounswe/bounswe2023group7#406]
### Issue Description

I evaluate the processes of the meetings with the customer for the team.

### Tasks

Parts of the task:
- [x] Revising the ps&customer meetings (1)

### Deadline of the Issue

03.11.2023 16:00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

03.11.2023 16:15

**Comment by mtkamiloglu** [comment]
I revied the issue and am closing
