### ISSUE TITLE
Revision of Wiki Side Bar for More Research Topics

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#41]
### Issue Description

We will be doing more research other than the assignments given by the project owner. Thus, the Research tab should be organized and categorized by favorite Github Repository/API research & chosen research topics by our team.

### Deadline of the Issue

20.03.2023 - 23.59

**Comment by melihgezerr** [comment]
I edited the sidebar and researches page based on that need. You can chech it from [here.](https://github.com/bounswe/bounswe2023group7/wiki/%F0%9F%93%9D-Researches) Can you review this and close it @SouthAscend ?

**Comment by elifkizilky** [comment]
I think we can remove the researches details part

**Comment by melihgezerr** [comment]
do you mean the extra page? i can delete the page and there will be only the sidebar. But in case of somethings get complicated,  it is good that we store all researches inside a real page.

**Comment by elifkizilky** [comment]
No, I mean this part:
![Ekran görüntüsü 2023-03-19 175719](https://user-images.githubusercontent.com/69367633/226185160-b2944e95-6a28-4b69-883e-4fa304787e2b.jpg)
Instead, it can be like this:
## 📝 [Researches](https://github.com/bounswe/bounswe2023group7/wiki/%F0%9F%93%9D-Researches)
<details>
<summary>Github Repository & API Researches</summary>

</details>

<details>
<summary>Chosen Researches by Our Team</summary>


</details>

**Comment by melihgezerr** [comment]
I changed it that way, thanks.
