### ISSUE TITLE
Implement Review Endpoints

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#412]
### Issue Description

The following endpoints will be created:

- Create review
- Like review
- Dislike review
- Edit review
- Delete review

### Tasks

Parts of the task:
- [x] #482
- [x] #486
- [x] #487
- [x] #488
- [x] #489

### Deadline of the Issue

21.11.2023 21.59

### Reviewer

@omersafakbebek 

### Deadline for the Review

21.11.2023 23.59

**Comment by melihgezerr** [comment]
this issue is done, need review.

**Comment by melihgezerr** [comment]
also you can close corresponding individual issues.
