### ISSUE TITLE
Mobile-Change Password Page

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#420]
### Issue Description

I will create a change password page and implement with endpoints.

### Tasks

Parts of the task:
- [x] Change password page for logged in user.
- [x] Implement it with backend endpoints.

### Deadline of the Issue

14.11.2023

### Reviewer

@kardelenerdal

### Deadline for the Review

14.11.2023

**Comment by senaal** [comment]
@kardelenerdal the task is completed and it can be seen here #446.

**Comment by kardelenerdal** [comment]
The PR is merged. I am closing the issue.
