### ISSUE TITLE
Review Component for Ludos Web

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#421]
### Issue Description

I will extract the review component that we used in game page as I did for post in home page.

### Deadline of the Issue

14.11.2023 - Tuesday - 00:00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

14.11.2023 - Tuesday - 15:00

**Comment by yunusemrealtug** [comment]
It needs review, linked to pull request.

**Comment by mtkamiloglu** [comment]
I reviewed and it looks perfect. Thank you for effort! I merged the branch.
