### ISSUE TITLE
Backend Connection of Follow-Unfollow Buttons for Ludos Web

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#422]
### Issue Description

We have designed the game page, but it has many buttons which will be linked to backend. One of them is follow/unfollow button. Its backend was prepared before and I will connect it to frontend side.

### Deadline of the Issue

14.11.2023 - Tuesday - 00:00

### Reviewer

@elifkizilky 

### Deadline for the Review

14.11.2023 - Tuesday - 15:00

**Comment by yunusemrealtug** [comment]
I linked the the pull request. @elifkizilky, may i get your feedback?

**Comment by elifkizilky** [comment]
I tested the code and I was able to follow/unfollow the game. Thank you for your time. Issue can be closed.
