### ISSUE TITLE
Mobile follow/unfollow a game implementation and backend connection

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#424]
### Issue Description

As part of the second milestone, we will deliver some of the requirements about game entity. Following and unfollowing a game will be delivered, too. Thus, after creating game summary widgets I will also implement necessary structures for follow/unfollow interaction.

### Tasks

Parts of the task:
- [x] Create layout and pages needed for follow/unfollow interaction
- [x] Connect created widgets to corresponding backend endpoint

### Extra Comments

None.

### Final Step

None

### Deadline of the Issue

14.11.2023 - Tuesday - 10:00

### Reviewer

@haticerk

### Deadline for the Review

14.11.2023 - Tuesday - 13:00

**Comment by frknlke** [comment]
Issue will be again in progress status after [dependent issue](https://github.com/bounswe/bounswe2023group7/issues/416) is completed.

**Comment by frknlke** [comment]
I completed subtasks and opened a [PR](https://github.com/bounswe/bounswe2023group7/pull/515). After approval issue will be closed.

**Comment by haticerk** [comment]
The following PR is approved. Nice job!
