### ISSUE TITLE
Home Page Design Revision

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#428]
### Issue Description

During the recent milestone demo, we received negative feedback and constructive suggestions regarding our home page design. To address this, we need to conduct a thorough review and make necessary changes to the design in accordance with the feedback received.

### Tasks

Parts of the task:
- [x] Design home page

### Deadline of the Issue

14.11.2023 21.59

### Reviewer

@mtkamiloglu 

### Deadline for the Review

14.11.2023 23.59

**Comment by elifkizilky** [comment]
I designed a new home page for our project. It is for the guest user view. The registered user will see his/her feed additionally and the components will be resized and replaced. 

My design is accessible via our Figma link. The design team can access the link via their emails. This issue needs to be reviewed.

**Comment by mtkamiloglu** [comment]
I reviewed the design from Figma and it looks better now with new placements. I am closing as completed
