### ISSUE TITLE
Research about Semantic Search

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#43]
### Issue Description

There need to be research about this topic as we discussed in [meeting #3](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%233-(17.03.2023))

### Tasks

Parts of the task:
- [ ] Researching and prepare documentation about semantic search
- [ ] Adding to wiki

### Deadline of the Issue

20.03.2023 - Monday - 23.59

### Reviewer

@melihgezerr 

### Deadline for the Review

20.03.2023 - Monday - 23.59

**Comment by tuluyhansozen** [comment]
@melihgezerr now it is waiting for review

**Comment by melihgezerr** [comment]
It is good, i reviewed it. Can you also add it to the sidebar and researches page. Then issue can be closed. thank you.
