### ISSUE TITLE
Games Page Design

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#435]
### Issue Description

I will design the game page for frontend and get opinions of my teammates.

### Tasks

Parts of the task:
- [x] Design the games page
- [x] Take feedback from my teammates

### Deadline of the Issue

13.11.2023 - Monday - 23.59

### Reviewer

@elifkizilky 

### Deadline for the Review

14.11.2023 - Tuesday - 15.00

**Comment by elifkizilky** [comment]
We can add a search bar to specifically search for the games providing options for filtering and sorting according to requirements. Such that when user completes the search, the resulting games will be shown on the page. 

Other than that, the game page design looks perfect. Thank you for your time.

**Comment by elifkizilky** [comment]
Okay, I'm closing this issue as completed.
