### ISSUE TITLE
Submitting the Final Lab Report #5

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#436]
### Issue Description

We have completed the lab report of this week. I will push it to the development branch.

### Tasks

Parts of the task:
- [x] Change lab report
- [x] Open pull request

### Deadline of the Issue

07.11.2023 - Tuesday - 22.00

### Reviewer

@kardelenerdal 

### Deadline for the Review

07.11.2023 - Tuesday - 22.00

**Comment by mtkamiloglu** [comment]
We have uploaded the final lab report. @kardelenerdal can you review and close the issue?

**Comment by kardelenerdal** [comment]
The PR is merged on 07.11. Thanks. I am closing the issue.
