### ISSUE TITLE
Revision of User Requirements 

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#45]
### Issue Description

User requirements are added on the requirements page. They should be reorganized and divided into subheadings.

### Deadline of the Issue

24.03.2023

### Reviewer

@mtkamiloglu 

### Deadline for the Review

25.03.2023

**Comment by elifkizilky** [comment]
First meeting regarding the revision of the user requirements are held on 23.03.2023 between 18:30 - 21:30 with @elifkizilky @senaal  @yunusemrealtug . Since, the work is still in progress, there will be another meeting.

**Comment by elifkizilky** [comment]
The requirements are revised and can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Requirements). The glossary and introduction parts are to be filled.

**Comment by mtkamiloglu** [comment]
I reviewed it and there is no problem. I am closing the issue
