### ISSUE TITLE
Revision of System Requirements

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#46]
### Issue Description

System requirements are added on the requirements page. They should be reorganized and divided into subheadings.

### Deadline of the Issue

24.03.2023

### Reviewer

@omersafakbebek 

### Deadline for the Review

25.03.2023

**Comment by elifkizilky** [comment]
First meeting regarding the revision of the user requirements are held on 23.03.2023 between 18:30 - 21:30 with @elifkizilky @senaal @yunusemrealtug . Since, the work is still in progress, there will be another meeting.

**Comment by omersafakbebek** [comment]
Review has been completed.
