### ISSUE TITLE
Edit game page in mobile

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#461]
### Issue Description

The user should be able to edit an existing game. I will create the page for it, but the backend connection will be implemented next week. 

### Deadline of the Issue

21.11.2023 - Tuesday - 12.00

### Reviewer

@frknlke 

### Deadline for the Review

21.11.2023 - Tuesday - 17.00

**Comment by kardelenerdal** [comment]
I created the front end of the edit game page. I used an example game id for the getGame endpoint. You can see the pages in this [branch](https://github.com/bounswe/bounswe2023group7/tree/feature/MB/461/edit_game_page). The PR will be opened when the backend endpoints are ready.

**Comment by frknlke** [comment]
Task is compeleted and pushed to the branch. Issue will be closed.
