### ISSUE TITLE
Annotation research

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#463]
### Issue Description

We need to make research on how to add annotation functionality in our web and mobile applications.

### Deadline of the Issue

21.11.2023 - Tuesday - 12.00

### Reviewer

@elifkizilky 

### Deadline for the Review

21.11.2023 - Tuesday - 17.00

**Comment by kardelenerdal** [comment]
In mobile applications, the annotations work like this: when you pick some text on a page, an Annotation button shows up. When you click it, you should be able to create an annotation using a text box. Then, there's a "See Annotations" button for others to check out the annotations for that item. The user should be able to delete their own annotation through here. I think the annotations should be available in forum posts and/or game pages.

**Comment by yunusemrealtug** [comment]
The implementation of it, as I understand, needs annotated values list for each user in backend side. On the user interface, user should be able to label and code should send the value to backend. Annotation is open to discussion. We can talk about in lab. https://mcamac.github.io/react-text-annotate/ This is one of the sources, we can use. However I am not sure this is sufficient.

**Comment by elifkizilky** [comment]
The research is done. The implementation of annotation will be at the final milestone. A more comprehensive discussion will be held later so that I'm closing this issue. Thank you for your time.
