### ISSUE TITLE
Game Review Functionality

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#468]
### Issue Description

Adding game review functionality to each game.

### Tasks

Parts of the task:
- [ ] Implement game review functionality for each game page.
- [ ] Connect it to backend.

### Deadline of the Issue

21.11.2023

### Reviewer

@haticerk

### Deadline for the Review

21.11.2023

**Comment by haticerk** [comment]
According to our plan, I will continue to this issue under #533. This issue can be closed.
