### ISSUE TITLE
Meeting Number #4 Notes

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#47]
### Issue Description

Meeting 4 is held on 22.03.2023. As a note-taker, I will create meeting page and share the notes.

### Tasks

Parts of the task:
- [x] Create the page 
- [x] Add meeting notes

### Deadline of the Issue

26.03.2023

### Reviewer

@frknlke 

### Deadline for the Review

27.03.2023

**Comment by elifkizilky** [comment]
The meeting #4 notes are added and can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%234-(22.03.2023)).

**Comment by frknlke** [comment]
Review has been completed. Issue will be closed.
