### ISSUE TITLE
Create Post Form Implementation

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#476]
### Issue Description

I will create the form that is needed when a post being created. I will design by referencing to forum creation page.

### Tasks

Parts of the task:
- [x] Implement the Post Creation Form

### Deadline of the Issue

21.11.2023 - Tuesday - 12.00

### Reviewer

@elifkizilky 

### Deadline for the Review

21.11.2023 - Tuesday - 15.00

**Comment by mtkamiloglu** [comment]
I implemented the forum post creation page. There we take three inputs: title, game that post is about and content of the post. I also added image add button but since backend is not implemented, it is not working. It looks like this:
<img width="1680" alt="Ekran Resmi 2023-11-21 09 15 12" src="https://github.com/bounswe/bounswe2023group7/assets/70536420/a3306468-6241-41c9-992a-b0fe128dcf4d">
Issue can be reviewed and closed. @elifkizilky

**Comment by elifkizilky** [comment]
I could not create a post when I tried. It gives the error code 403. When I looked at it, the request body is not the same as the one in the swagger documentation. We can postpone the merge of this branch until the backend is ready if that is suitable. Also a tags selection section should be added

**Comment by elifkizilky** [comment]
Since the page is created and the related revision issue is opened, I'm closing this issue as completed. Thank you for your time
