### ISSUE TITLE
Revision of Non-Functional Requirements

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#48]
### Issue Description

Non-functional requirements are added on the requirements [page](https://github.com/bounswe/bounswe2023group7/wiki/Requirements-(Draft)). They should be reorganized and divided into subheadings.

### Deadline of the Issue

24.03.2023

### Reviewer

@tuluyhansozen 

### Deadline for the Review

25.03.2023

**Comment by elifkizilky** [comment]
First meeting regarding the revision of the user requirements are held on 23.03.2023 between 18:30 - 21:30 with @elifkizilky @senaal @yunusemrealtug . Since, the work is still in progress, there will be another meeting.

**Comment by yunusemrealtug** [comment]
The non-functional requirements are revised and can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Requirements). The glossary and introduction parts are to be filled.

**Comment by tuluyhansozen** [comment]
I checked and closed
