### ISSUE TITLE
Profile Page Mock-up for Mobile 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#50]
### Issue Description

We should create profile page mockups for mobile devices

### Tasks

Parts of the task:
- [x]  Analyzing the web mock up
- [x] Creating mock up for mobile

### Deadline of the Issue

28.03.2023

### Reviewer

@senaal

**Comment by tuluyhansozen** [comment]
It took longer than I expected. Sorry for delaying.

**Comment by melihgezerr** [comment]
It needs more revision but i am closing it for tihs issue.
