### ISSUE TITLE
Login Page Mock-up for Mobile 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#51]
### Issue Description

We should create profile page mockups for mobile devices

### Tasks

Parts of the task:
- [x]  Analyzing the web mock up
- [x]   Creating mock up for mobile

### Deadline of the Issue

28.03.2023

### Reviewer

@elifkizilky

**Comment by elifkizilky** [comment]
The login page for mobile application is already done last week by me. The work can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Mock-Ups). Thus, I'm closing this issue
