### ISSUE TITLE
Entity Page for Ludos Web

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#512]
### Issue Description

The game has entity features. The page will be added for characters, packages/dlcs, environments, items of games.

### Deadline of the Issue

04.12.2023 - Monday - 23.59

### Reviewer

@mtkamiloglu 

### Deadline for the Review

05.12.2023 - Monday - 15.00

**Comment by yunusemrealtug** [comment]
We did not add entity pages to scenerio. Additionally, other issues assigned to me caused me to effort than I expected . Therefore, we decided to modify deadline of the issue.

**Comment by mtkamiloglu** [comment]
I merged the pr, so I am closing this issue.
