### ISSUE TITLE
Making Mobile & Frontend Tags and Platforms Consistent

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#513]
### Issue Description

In our create game forums, there is an inconsistency between the tag and platform choosing. We will resolve this issue and make the frontend and mobile application compatible.

### Tasks

Parts of the task:
- [x] Meet and discuss the inconsistencies
- [x] Resolve them

### Deadline of the Issue

27.11.2023 21.59

### Reviewer

@haticerk 

### Deadline for the Review

27.11.2023 23.59

**Comment by kardelenerdal** [comment]
Hi, here are the **age restriction** options for mobile for now:
- 'Early Childhood',
-  'Everyone',
- 'Everyone 10 and older',
- 'Teen',
- 'Mature',
- 'Adults Only',
- 'Rating Pending',
 
The **platform** options: 
-  'Android',
- 'iOS',
- 'Windows',
- 'macOS',
- 'Linux',
- 'PlayStation',
- 'Xbox',
- 'Nintendo',
- 'Board Game'

The **tags**, **predecessors** and **successors** are not restricted to options, user can define anything. 
How can we ensure that our mobile aligns well with the frontend? Also, could you provide the options in the frontend?

**Comment by elifkizilky** [comment]
For the frontend, 

### platforms:

-  "PC",
-   "PlayStation",
-   "Xbox",
-   "Nintendo Switch",
-   "Mobile",
-   "VR",
-   "Web Browser"

### Age restrictions:

- 3+
- 7+
- 12+
- 16+
- 18+

### Tags:

- "Action",
- "Adventure",
- "RPG",
- "Strategy",
- "Simulation"



**For age restrictions**; I searched for the pegi options on the Internet. I think using PEGI would be suitable because the games are also coming with this information, it is easy to assign this way.

**For tags**; I think we should have some predefined tags but we should expand the current ones. Users may be able create custom tags but handling these may be overwhelming for the search functionality; so I prefer having predefined options to users for tag selection.

**For platforms**, we can merge our platform options, that would be better.


What do you think?

**Comment by kardelenerdal** [comment]
**Platforms:**

- 'Android',
- 'iOS',
- 'Windows',
- 'macOS',
- 'Linux',
- 'PlayStation',
- 'Xbox',
- 'Nintendo Switch',
- 'Board Game'
- 'VR'

**Ages:**

- 3+
- 7+
- 12+
- 16+
- 18+

For tags, I found these options on Internet. But I think it is too much. We should have ~15 options for better experience in my opinion.
**Tags:**

- Action
- Adventure
- RPG
- Strategy
- Simulation
- Sports
- Fighting
- Horror
- Puzzle
- Multiplayer
- Indie
- RTS
- Racing
- Open World
- Educational
- VR
- Survival
- Story-Driven
- Retro
- Anime
- Hack and Slash
- Mystery
- Historical
- Sci-Fi
- Fantasy
- Comedy
- Artistic
- Puzzle-Platformer

**Comment by elifkizilky** [comment]
I think these are okay, even if they are many they are all related to games. We can get feedback from customers as well.

**Comment by elifkizilky** [comment]
Both mobile and frontend team arranged their contents so this issue can be closed after review @haticerk .

**Comment by haticerk** [comment]
Thank you for your efforts, girls! These tags and platforms are sufficient right now.
