### ISSUE TITLE
Update the location of the create game button

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#521]
### Issue Description

The "Create Game" button in the games page should be at the top of the page even if the user scrolls to the bottom.

### Deadline of the Issue

27.11.2023 - Monday- 12.00

### Reviewer

@frknlke 

### Deadline for the Review

27.11.2023 - Monday- 17.00

**Comment by frknlke** [comment]
PR merged into development. Further review is not needed.
