### ISSUE TITLE
Make the fields of the game static

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#524]
### Issue Description

According to the final decision of [523](https://github.com/bounswe/bounswe2023group7/issues/513), I will update the create game and edit game pages. 

### Tasks

Parts of the task:
- [x] Change the options in edit game page.
- [x] Change the options in create game page.

### Final Step

The games with different tags/etc. than the decided options should be removed from the database.

### Deadline of the Issue

27.11.2023 - Monday- 12.00

### Reviewer

@haticerk 

### Deadline for the Review

27.11.2023 - Monday- 17.00

**Comment by haticerk** [comment]
As I see, the following PR is merged. Thank you for your time and efforts!
