### ISSUE TITLE
Creating Meeting Notes 6

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#542]
### Issue Description

We had a face to face meeting on 23.11.2023 to discuss our presentation and report as mentioned in #509 . The report should be written.

### Deadline of the Issue

27.11.2023 - Monday- 12.00

### Reviewer

@haticerk 

### Deadline for the Review

27.11.2023 - Monday- 17.00

**Comment by kardelenerdal** [comment]
The meeting notes can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%236-23.11.2023).

**Comment by haticerk** [comment]
Thank you for writing the meeting notes. Well done!
