### ISSUE TITLE
Creating Milestone 2 Report Template

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#543]
### Issue Description

We need a template for milestone report so we can work efficiently.

### Tasks

Parts of the task:
- [x] Create template
- [x] Share with the group

### Deadline of the Issue

24.11.2023 21.59

### Reviewer

@senaal 

### Deadline for the Review

24.11.2023 23.59

**Comment by elifkizilky** [comment]
I created the milestone 2 report template in hackmd and shared the editing link with the group. The issue needs to be reviewed.

**Comment by senaal** [comment]
The task is completed, thus I am closing the issue.
