### ISSUE TITLE
Game Page Image Orientation

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#545]
### Issue Description

In the game page, the image orientation is not working properly. While creating a game, we are uploading the image, there is no problem in that but when i go to the game's page, the image size is not adjusted. We can add a wrapper to it to fix its size.  Can you look at it @yunusemrealtug?

### Related Image: 

![image](https://github.com/bounswe/bounswe2023group7/assets/69367633/72ee14c0-811c-4eb5-952f-144fcbcc0c88)

### Deadline of the Issue

27.11.2023 19.00

### Reviewer

@elifkizilky 

### Deadline for the Review

27.11.2023 20.00

**Comment by yunusemrealtug** [comment]
Good catch, i will fix it.
