### ISSUE TITLE
Deciding the tags & platforms to be used in our platform

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#549]
### Issue Description

As also mentioned in #513 , we should synch the platforms and tags to be used in our platform. For this, we should decide on the tags and platforms to be used as a team. We can discuss under this issue.

### Deadline of the Issue

27.11.2023 19.00

### Reviewer

@haticerk 

### Deadline for the Review

27.11.2023 20.00

**Comment by haticerk** [comment]
I reviewed the issue #513. Thank you for your time.
