### ISSUE TITLE
Provide Progress According to Requirements

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#565]
### Issue Description

being either not started, in progress, or completed. 

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

01.12.2023

### Reviewer

@fur

### Deadline for the Review

01.12.2023

**Comment by melihgezerr** [comment]
this issue needs review. @frknlke

**Comment by frknlke** [comment]
I reviewed the work. All requirements correctly marked regarding their current state in the project. Well done. Issue will be closed.
