### ISSUE TITLE
Class Diagram - Annotation

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#57]
### Issue Description

As we discussed in Meeting 5, we will create class diagrams to understand how we are going to implement the project. This issue focuses on designing the class diagram for Annotation.

### Tasks

Parts of the task:
- [x] Distinguish relationships.
- [x] Create the structure.

### Extra Comments

Checking information at this [link](https://creately.com/blog/software-teams/class-diagram-tutorial/) can provide a good foundation of how to create class diagrams.

### Final Step

After finishing this task, I will do research about sequence diagrams.

### Deadline of the Issue

03.04.2023 - Monday - 21:00

### Reviewer

@senaal

### Deadline for the Review

04.04.2023 - Tuesday - 11:00

**Comment by frknlke** [comment]
I completed my part in class diagram. I added Annotation class to the diagram. After all part complete, final result will be published on the [class diagram page](https://github.com/bounswe/bounswe2023group7/wiki/Class-Diagrams). For now, the part I did can be seen below.


![Opera Anlık Görüntü_2023-04-04_003826_lucid app](https://user-images.githubusercontent.com/61520034/229633355-c39fd279-6229-4126-8034-b2ba86804c6a.png)

**Comment by senaal** [comment]
I checked that also in Lucidchart, the task is completed and I am closing the issue.
