### ISSUE TITLE
Adding 2 new fields to ReviewGetInfoResponseDto

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#573]
### Issue Description

We need to add isLikedByUser/isDislikedByUser fields to get flows.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

26.11.2023

### Reviewer

@yunusemrealtug 

### Deadline for the Review

26.11.2023

**Comment by yunusemrealtug** [comment]
https://github.com/bounswe/bounswe2023group7/pull/574 The pull request is there. I had reviewed in pull request.
