### ISSUE TITLE
Creating Group Finding Mockup & Revision

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#58]
### Issue Description

I will create another mockup for group finding feature and will make small changes on mockup.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

05.04.2023

### Reviewer

@elifkizilky 

### Deadline for the Review

07.04.2023

**Comment by elifkizilky** [comment]
The work is completed and can be seen [here](https://github.com/bounswe/bounswe2023group7/wiki/Mock-Ups).
