### ISSUE TITLE
Login Page Height Problem

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#586]
### Issue Description

Below of the login page looks like this:

![image](https://github.com/bounswe/bounswe2023group7/assets/69367633/f232f0c9-3f02-4783-a443-f06ca9296e37)

It should be resolved

### Deadline of the Issue

01.11.23

### Deadline for the Review

01.11.23

**Comment by yunusemrealtug** [comment]
Deadline is in the past?
