### ISSUE TITLE
Describe the Planned vs. Actual on the Milestone Report

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#591]
### Issue Description

As a part of the milestone report, we need to describe the changes and their impact on our project after milestone 1.

### Deadline of the Issue

1 December 2023 - Friday - 3 pm

### Reviewer

@frknlke 

### Deadline for the Review

1 December 2023 - Friday - 5 pm

**Comment by frknlke** [comment]
I reviewed the work. All changes were summarized clearly. Well done. Issue will be closed.
