### ISSUE TITLE
Remove Random Test Data from Database for Customer Presentation

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#595]
### Issue Description

We've got some random test data in our database from checking our backend endpoints. Before showing things to the customer, we need to remove them. This way, our presentation looks clean and neat.

### Final Step

We will check from both mobile and frontend that games can be loaded successfully.

### Deadline of the Issue

27.11.2023 - Monday- 20.00

### Reviewer

@haticerk 

### Deadline for the Review

27.11.2023 - Monday- 21.00

**Comment by haticerk** [comment]
Nice work! Our app needed this, thank you :)
