### ISSUE TITLE
Creating .apk file for Milestone 2

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#596]
### Issue Description

We need to build and publish .apk file for Milestone 2. 

### Tasks

Parts of the task:
- [x] Creating .apk file.
- [ ] Add it to release.

### Final Step

After publishing .apk file, we need to try it on an Android phone.

### Deadline of the Issue

27.11.2023 - Monday- 21.30

### Reviewer

@furk

### Deadline for the Review

27.11.2023 - Monday- 22.00

**Comment by frknlke** [comment]
I tried .apk on my own mobile phone it works correctly. No further review is needed.
