### ISSUE TITLE
Editing Mock-Up Wiki Page

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#60]
### Issue Description

There are outdated mockup pdfs and mess in the page like there is "mock-up" and "mock-ups" link. I will edit and update the page after i finished my [issue#58](https://github.com/bounswe/bounswe2023group7/issues/58).

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

05.04.2023

### Reviewer

@melihgezerr 

### Deadline for the Review

07.04.2023

**Comment by melihgezerr** [comment]
This issue is extended due to mockup revisions.

**Comment by elifkizilky** [comment]
We added some mock-ups today as a group but there are still some mock-ups waiting to be added. Also, some of them are in the revision process.

**Comment by elifkizilky** [comment]
I deleted the pdf and added the images of all mock-ups by categorizing them. I arranged their sizes for coherency. The page can be accessed by this [link](https://github.com/bounswe/bounswe2023group7/wiki/Mock-Ups).
