### ISSUE TITLE
List and Status of Deliverables

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#600]
### Issue Description

For milestone report, I will create a list about deliverables. Also I will explain their status and I will add a brief information about deliverable.

### Tasks

Parts of the task:
- [x] Document deliverables and their status
- [x] Add them to the milestone report

### Deadline of the Issue

30.11.2023

### Reviewer

@mtkamiloglu

### Deadline for the Review

01.12.2023

**Comment by senaal** [comment]
The task needs review, @mtkamiloglu

**Comment by mtkamiloglu** [comment]
Issue is closed as completed.
