### ISSUE TITLE
Game Story and Average Rating In Game Pages

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#603]
### Issue Description

In game pages and game summaries, we don't have average rating. We need to add it with rating icon. Also, in Games page, there is the default string for game stories. Since the backend task is done now, we can change it. 

### Tasks

Parts of the task:
- [x] Changing Average Rating
- [x] Changing Game Story

### Deadline of the Issue

27.11.2023 - Monday- 20.00

### Reviewer

@frknlke 

### Deadline for the Review

27.11.2023 - Monday- 21.00

**Comment by frknlke** [comment]
PR merged into development successfully. Review is not needed.
