### ISSUE TITLE
Bugfix: Like/Dislike Functionality

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#605]
### Issue Description

There is a bug in like/dislike functions.

### Deadline of the Issue

27 November 2023 - Monday- 9pm

### Reviewer

@senaal 

### Deadline for the Review

27 November 2023 - Monday - 10pm

**Comment by haticerk** [comment]
This bug still on. It needs to solve.

**Comment by haticerk** [comment]
The issue is solved in #684. It can be reviewed.

**Comment by senaal** [comment]
The issue is fixed, now I am closing the issue.
