### ISSUE TITLE
Update Individual Contribution Report Template

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#616]
### Issue Description

The individual contribution report should be updated according to the given aspects by the teachin asistants.

### Tasks

Parts of the task:
- [x] Update the template
- [x] Share with the group

### Deadline of the Issue

28.11.2023 19.00

### Reviewer

@senaal 

### Deadline for the Review

28.11.2023 21.00

**Comment by elifkizilky** [comment]
The template is updated and can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-Template). This issue needs to be reviewed.

**Comment by senaal** [comment]
It looks great. I am closing the issue.
