### ISSUE TITLE
Writing General Test Plan for The Project - Milestone 2

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#623]
### Issue Description

I will write our general test plan for the project in scope of milestone 2 report. 

### Tasks

Parts of the task:
- [x] Write the general test plan for the project.

### Deadline of the Issue

01.12.2023 - Friday - 15.00

### Reviewer

@elifkizilky 

### Deadline for the Review

01.12.2023 - Friday - 16.30

**Comment by mtkamiloglu** [comment]
I wrote the general test plan for the frontend. It can be reviewed from [here](https://hackmd.io/q384OUXKTAKo0HX8yUItow#for-frontend) @elifkizilky

**Comment by elifkizilky** [comment]
This issue can be closed since the related part is completed.
