### ISSUE TITLE
Individual Contribution Report - Yunus Emre Altuğ

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#624]
### Issue Description

For the milestone 2, I must write my contribution report.

### Deadline of the Issue

01.12.2023 - Friday - 15:00

### Reviewer

@frknlke 

### Deadline for the Review

01.12.2023 - Friday - 17:00

**Comment by yunusemrealtug** [comment]
I completed my part

**Comment by frknlke** [comment]
I reviewed the work. Well done. Issue will be closed.
