### ISSUE TITLE
Use Case Diagram - Event Actions

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#63]
### Issue Description

As we discussed in Meeting 5, we will create class diagrams to understand how we are going to implement the project. I will prepare use case diagram for events.

### Tasks

Parts of the task:
- [x] Determining the actions.
- [x] Adjusting connection between them.

### Extra Comments

_No response._

### Final Step

_No response._

### Deadline of the Issue

04.04.2023 - Tuesday - 11.00

### Reviewer

@melihgezerr 

### Deadline for the Review

04.04.2023 - Tuesday - 23.59

**Comment by yunusemrealtug** [comment]
I added use case diagram for event. Issue needs review now.

**Comment by melihgezerr** [comment]
i am closing this issue. you can find the diagram [here](https://github.com/bounswe/bounswe2023group7/wiki/Use-Case-Diagrams).
