### ISSUE TITLE
Class Diagram - Administration & Events

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#64]
### Issue Description

I will prepare two parts of the class diagram. These parts are based on admins' capabilities and event features.

### Tasks

Parts of the task:
- [x] Preparing event class diagram.
- [x] Preparing administation class diagram.

### Deadline of the Issue

04.04.2023 - Tuesday - 11.00

### Reviewer

@frknlke 

### Deadline for the Review

04.04.2023 - Tuesday - 23.59

**Comment by yunusemrealtug** [comment]
The task is done and needs review. I created classes admin, event and event comment and connected them to main diagram.

**Comment by frknlke** [comment]
The work has been successfully completed. I am closing the issue.
