### ISSUE TITLE
User Suggested Games

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#640]
### Issue Description

user suggested games endpoint will be implemented

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

09.12.2023

### Reviewer

@tacettinburakeren 

### Deadline for the Review

12.12.2023

**Comment by melihgezerr** [comment]
this issue is related to #639

**Comment by omersafakbebek** [comment]
This issue was handled with [#683](https://github.com/bounswe/bounswe2023group7/pull/683).
