### ISSUE TITLE
Rating Bar Functionality

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#661]
### Issue Description

I will connect rating bar to the backend. 

### Tasks

Parts of the task:
- [x] Connection of rating bar to related endpoint.

### Deadline of the Issue

12.12.2023

### Reviewer

@kardelenerdal

### Deadline for the Review

12.12.2023

**Comment by kardelenerdal** [comment]
I reviewed your code from the branch and tested in my local. Thank you for your efforts.
