### ISSUE TITLE
Class Diagram - Post

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#67]
### Issue Description

 I will be doing the class diagram for the post part.

### Tasks

Parts of the task:
- [x] create post part for class diagram

### Deadline of the Issue

07.04.2023

### Reviewer

@mtkamiloglu 

### Deadline for the Review

08.04.2023

**Comment by senaal** [comment]
Post class diagram is done and it is visible at Lucidchart, it needs review.
![post](https://user-images.githubusercontent.com/98026115/230750701-944f4819-d55b-41b7-a958-bb8d20d11f3a.png)

**Comment by mtkamiloglu** [comment]
I reviewed the class diagram and closing it.
