### ISSUE TITLE
Class Diagram - Tag

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#68]
### Issue Description

I will be doing the class diagram for the tag part.

### Tasks

Parts of the task:
- [x] create tag part for class diagram

### Deadline of the Issue

07.04.2023

### Reviewer

@frknlke 

### Deadline for the Review

08.04.2023

**Comment by senaal** [comment]
Tag class diagram is done and it is visible at Lucidchart, it needs review.
![tag](https://user-images.githubusercontent.com/98026115/229648255-8f5659f1-0e1e-4f15-bb1d-2d250667de4b.png)

**Comment by frknlke** [comment]
The work has been successfully completed. I am closing the issue.
