### ISSUE TITLE
User Levels Implementation

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#688]
### Issue Description

I need to add our mail address in user page for applying e-sport or developer accounts. And change the user page information accordingly.

### Deadline of the Issue

19.12.2023 - Tuesday - 12.00

### Reviewer

@senaal 

### Deadline for the Review

19.12.2023 - Tuesday - 15.00

**Comment by elifkizilky** [comment]
We can discuss about how and what should we write it to be coherent as frontend & mobile team!
