### ISSUE TITLE
Use Case Diagram - View Game Page

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#69]
### Issue Description

As we discussed in meeting 5, I will prepare use case diagram for viewing home page

### Deadline of the Issue

04.04.2023-Tuesday-11.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

04.04.2023-Tuesday-23.59

**Comment by omersafakbebek** [comment]
Use case diagram for viewing game page can be reviewed.

**Comment by yunusemrealtug** [comment]
There is no problem as I see in the diagram for in this part. I'm closing the issue. Have a nice day.
