### ISSUE TITLE
Sequence Diagram - Create Post

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#71]
### Issue Description

As we discussed in meeting 6, I will prepare sequence diagram for Create Post action.

### Tasks

Parts of the task:
- [x] Sequence diagram for Create Post action

### Deadline of the Issue

08.04.2023-Saturday-17.00

### Reviewer

@frknlke 

### Deadline for the Review

08.04.2023-Saturday-23.59

**Comment by omersafakbebek** [comment]
Sequence diagram for creating a post can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/Sequence-Diagrams).

**Comment by frknlke** [comment]
I did review the sequence diagrams and not encounter an error. I am closing the issue.
