### ISSUE TITLE
Frontend and Mobile Team Peer Testing

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#715]
### Issue Description

As frontend and mobile teams, we will test our UIs as peer groups. The mobile team will test frontend UI and the frontend team will test mobile UI. We will give feedback to each other. We can write our feedback under this issue.

Please open issues if you encounter a problem in the UI and mention them under this issue, it is easier to keep track of them.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Extra Comments

This issue will stay open until the milestone, please contribute so that we can enhance our UI/UX 😄 

### Deadline of the Issue

25.11.2023 21.59

### Reviewer

@omersafakbebek 

### Deadline for the Review

25.11.2023 23.59

**Comment by haticerk** [comment]
We have done the peer testing, and made some updates according to feedbacks.

**Comment by omersafakbebek** [comment]
It seems that the process went well and was beneficial. Good job.
