### ISSUE TITLE
Sequence Diagram - Create Review

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#72]
### Issue Description

As we discussed in meeting 6, I will prepare sequence diagram for Create Review action.

### Tasks

Parts of the task:
- [x] Sequence diagram for Create Review action

### Deadline of the Issue

08.04.2023-Saturday-17.00

### Reviewer

@elifkizilky 

### Deadline for the Review

08.04.2023-Saturday-23.59

**Comment by omersafakbebek** [comment]
Sequence diagram for creating a review can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/Sequence-Diagrams).

**Comment by elifkizilky** [comment]
The wrong parts are corrected and the work is completed. The issue can be closed.
