### ISSUE TITLE
Unsigned User Drawer Photo

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#722]
### Issue Description

The unsigned user does not see anything in drawer. But in that bug, the unsigned user can see error message.

### Deadline of the Issue

16.12.2023

### Reviewer

@frknlke

### Deadline for the Review

16.12.2023

**Comment by senaal** [comment]
The issue needs review.

**Comment by frknlke** [comment]
PR merged into the development branch. Well done. Issue will be closed.
