### ISSUE TITLE
Create Game Page Rendering Bug

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#728]
### Issue Description

After creating game, the route does not work, but if it is refreshed it is working. 
![image](https://github.com/bounswe/bounswe2023group7/assets/100098311/b144878c-9658-4fc8-8611-4004f506308a)

### Deadline of the Issue

28.12.2023 - Thursday - 11.00

**Comment by elifkizilky** [comment]
Also, when navigating from a game page to another game page, same issue is triggered.
### Possible Solution: 
Triggering rendering when the game title is changed can be added.

**Comment by elifkizilky** [comment]
problem is solved, created PR.
