### ISSUE TITLE
Meeting #6 Notes

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#74]
### Issue Description

Today's meeting 6 (05.04.2023) will be shared in our wiki page according to meeting notes template

### Tasks

Parts of the task:
- [x] Create page
- [x] Add meeting notes
- [x] Add it to wiki page

### Deadline of the Issue

06.04.2023 23.59

### Reviewer

@senaal 

### Deadline for the Review

07.04.2023 23.59

**Comment by senaal** [comment]
Review has been completed. Issue will be closed.
