### ISSUE TITLE
Change "Image Link" field in create entity forum to sync with mobile

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#740]
### Issue Description

In the mobile and frontend, the create entity form should be coherent in order to have a consistent entity page. Therefore, the "Image Link" field name should change to "Image". Otherwise, we are interpreting the image field falsely in frontend.

### Deadline of the Issue

-

**Comment by mtkamiloglu** [comment]
I opened a pull request and attach it to this issue. After pr is merged this issue can be closed.
