### ISSUE TITLE
Class Diagram - PersonalInfo & Achievement & Activity & Report

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#75]
### Issue Description

Additional classes PersonalInfo, Achievement, and Activity will be organized. Additionally, the relationship between other classes will be revised.

### Tasks

Parts of the task:
- [x] Organize PersonalInfo, Achievement, Activity classes
- [x] Revise the relations
and 

### Final Step

After finishing this task, I will check the User class because User class is related to those classes.

### Deadline of the Issue

08.04.2023 17.00

### Reviewer

@omersafakbebek 

### Deadline for the Review

09.04.2023

**Comment by elifkizilky** [comment]
The work can be seen here:
![image](https://user-images.githubusercontent.com/69367633/230655396-b4e4fb33-5737-4fc5-a8c3-c130c6e259db.png)
Issue needs revirew.

**Comment by omersafakbebek** [comment]
The review has been completed. The task is done.
