### ISSUE TITLE
Preparation of Final Milestone report

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#759]
### Issue Description

Milestone report should be prepared. The task division will be made later.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

29.12.23 12.00

### Reviewer

@elifkizilky @haticerk @kardelenerdal 

### Deadline for the Review

29.12.23 15.00

**Comment by haticerk** [comment]
We finalized and submitted the report. Thank you everyone!
