### ISSUE TITLE
Class Diagram - Gamer & E-sport Player & Developer & Promotion

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#76]
### Issue Description

Gamer, E-sport Player, Developer, and Promotion classes will be organized. Afterward, the relationship between other classes will be checked.

### Tasks

Parts of the task:
- [x] Organize the gamer, e-sport player, developer, promotion classes
- [x] Revise the relationship between other classes

### Final Step

After finishing this task, I will check the User class because User class is related to those classes.

### Deadline of the Issue

08.04.2023 17.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

09.04.2023 18.00

**Comment by elifkizilky** [comment]
The classes can be seen here:
![image](https://user-images.githubusercontent.com/69367633/230655115-d48d55f6-5ada-4f43-a56e-b57fe027e342.png)
Work needs review.

**Comment by yunusemrealtug** [comment]
It meets class diagram rules and explains classes' structures. I am closing the issue.
