### ISSUE TITLE
Preparation of Individual report

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#760]
### Issue Description

Everyone should prepare their own reports for the final milestone.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

29.12.23 12.00

### Reviewer

-

### Deadline for the Review

29.12.23 15.00

**Comment by haticerk** [comment]
Everyone created her/his contribution report and we submitted it in the final report. This issue can be closed.
