### ISSUE TITLE
Preparation of Final Milestone deliverables

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#762]
### Issue Description

Assistants shared a document with us about the deliverables. We need to prepare those deliverables and of course, deliver. Task divison will be made later.

### Tasks

Parts of the task:
- [ ] Divide tasks
- [x] Prepare

### Deadline of the Issue

29.12.23 12.00

### Reviewer

everyone

### Deadline for the Review

29.12.23 15.00

**Comment by haticerk** [comment]
We shared the load of the report and finalized the milestone. Thank you everyone!
