### ISSUE TITLE
Sequence Diagram - Edit Profile Page

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#78]
### Issue Description

A sequence diagram for the edit profile page will be made.

### Deadline of the Issue

08.04.2023 17.00

### Reviewer

@tuluyhansozen 

### Deadline for the Review

09.04.2023 18.00

**Comment by elifkizilky** [comment]
Sequence diagram for editing profile page can be seen below.
![edit profile](https://user-images.githubusercontent.com/69367633/230724099-e0d44e0a-e0fb-4649-86b0-f70168b0e039.jpeg)
The work needs review.

**Comment by tuluyhansozen** [comment]
I reviewed it
