### ISSUE TITLE
Sequence Diagram - Ban User

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#80]
### Issue Description

I will create a sequence diagram for ban user usecase of admin.

### Deadline of the Issue

08.04.2023 - Saturday - 16.00

### Reviewer

@yunusemrealtug

### Deadline for the Review

09.04.2023 - Monday - 16.00

**Comment by mtkamiloglu** [comment]
<img width="796" alt="Ekran Resmi 2023-04-08 13 15 04" src="https://user-images.githubusercontent.com/70536420/230715881-4289741e-774b-4a41-a9f7-4f6cb959ad9e.png">
I created the sequnce diagram for ban user from commenting. If deemed necessary I can create more admin sequence diagram.

**Comment by mtkamiloglu** [comment]
since it is necessary, the sequence diagram has been changed as follows:
![ba56792b-f4d7-487c-81f4-b8eb2b390574](https://user-images.githubusercontent.com/70536420/230763810-86d10a37-f2d1-4866-a384-fb374c255391.jpeg)

**Comment by yunusemrealtug** [comment]
The diagram seems adequate currently. Closing.
