### ISSUE TITLE
Class Diagram - Review

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#81]
### Issue Description

As we discussed in meeting 6, I will create class diagram for review.

### Deadline of the Issue

08.04.2023 - Saturday - 16.00

### Reviewer

@yunusemrealtug

### Deadline for the Review

09.04.2023 - Monday - 16.00

**Comment by mtkamiloglu** [comment]
<img width="861" alt="Ekran Resmi 2023-04-08 12 23 53" src="https://user-images.githubusercontent.com/70536420/230714075-7faa02bd-378a-42cb-87f7-cf856e0b7f83.png">

I created review class diagram and connected it with the relevant classes.

**Comment by yunusemrealtug** [comment]
You have added constructor to diagram, so I am closing now.
![image](https://user-images.githubusercontent.com/100098311/230774061-9090ec35-c7e3-4243-a752-11ffffe95359.png)
