### ISSUE TITLE
Use Case Diagram - Annotation

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#82]
### Issue Description

We need to add use case diagram for annotation to our main diagram.

### Tasks

Parts of the task:
- [x] Create use case diagram for annotation

### Extra Comments

_No Response_

### Deadline of the Issue

08.04.2023 - Saturday - 18:00

### Reviewer

@yunusemrealtug

### Deadline for the Review

09.04.2023 - Sunday - 18:00

**Comment by frknlke** [comment]
I formed the use case diagram for Annotation. Result is following:
<br/>
![Annotation - Use Case](https://user-images.githubusercontent.com/61520034/230665637-ed14b08a-b577-43cc-bae7-02eedb9a8c5a.png)

Review is needed.

**Comment by yunusemrealtug** [comment]
No problem, closing the issue.
