### ISSUE TITLE
Sequence Diagram - Event Actions

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#87]
### Issue Description

A sequence diagram for the event actions will be made.

### Deadline of the Issue

08.04.2023 - Saturday - 17.00

### Reviewer

@elifkizilky 

### Deadline for the Review

09.04.2023 - Sunday - 18.00

**Comment by yunusemrealtug** [comment]
You can visit my work below event header from this [link](https://github.com/bounswe/bounswe2023group7/wiki/Sequence-Diagrams). Now issue needs review.

**Comment by elifkizilky** [comment]
The work is reviewed and done completely. The issue can be closed.
