### ISSUE TITLE
Annotations for Web - Milestone report

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#870]
### Issue Description

I will write an explanation about annotation for the web covering those:

- Status
- Compliance with W3C WADM
- Implementation description

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

29.12.23 21.00

### Reviewer

@haticerk 

### Deadline for the Review

29.12.23 22.00

**Comment by haticerk** [comment]
I read the part, it looks wonderful. Nice job!
