### ISSUE TITLE
Video for the Project

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#871]
### Issue Description

We will make video of our system being used with a good scenario as asked in the final deliverables.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

29.12.23 21.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

29.12.23 22.00

**Comment by kardelenerdal** [comment]
We recorded the video. Here is the link: https://www.youtube.com/watch?v=x_eCsi_eU8Y

**Comment by yunusemrealtug** [comment]
The site is clearly explained. Thanks for the effort.
