### ISSUE TITLE
UI/UX for Mobile - Milestone Report

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#873]
### Issue Description

For the final milestone report, I will list user Interface designs and the links to the source code in the project repository.

### Tasks

Parts of the task:
- [x] Add  UI designs taken as screen capture
- [x] Add links for corresponding source code

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

29.12.2023 - Friday - 13:00

### Reviewer

@kardelenerdal

### Deadline for the Review

29.12.2023 - Friday - 16:00

**Comment by frknlke** [comment]
I completed my part. Result can be viewed by group members by hackmd link. It will be visible to all when all works related to Final Milestone merged. Review is absolutely needed to ensure there is no missing part.

**Comment by kardelenerdal** [comment]
Hi Furkan, I read your part in the report. It looks very good, you included every feature in our app. Thank you for your hard work.

**Comment by senaal** [comment]
I reviewed the parts you finished. It looks very nice and explains our functions quite well. Thank you for your effort.
