### ISSUE TITLE
Mobile Instructions for Use with an Emulator

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#875]
### Issue Description

I will provide instructions for use with an emulator for the mobile application.

### Deadline of the Issue

29.12.2023

### Reviewer

@haticerk

### Deadline for the Review

29.12.2023

**Comment by senaal** [comment]
The task is finished and shared in our group. It can be seen here. Review is needed.

**Comment by haticerk** [comment]
Nice job, well done!
