### ISSUE TITLE
Final Milestone - User Manual for Mobile App

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#877]
### Issue Description

For the Final Milestone Report, I will prepare user manual to help a new user to get familiar with app by giving clear directives.

### Tasks

Parts of the task:
- [x] Create user manual for the mobile app.

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

29.12.2023 - Friday - 15:00

### Reviewer

@senaal

### Deadline for the Review

29.12.2023 - Friday - 17:00

**Comment by frknlke** [comment]
I completed my part. Currently work can be viewed by hackmd link by other team members. It will be published with other milestone deliverables as a whole. Review is needed.

**Comment by senaal** [comment]
I reviewed the user manual. It was very detailed and easy to understand. Thanks for your efforts. I am closing the issue as completed.
