### ISSUE TITLE
Final Milestone Report - Scenario 

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#880]
### Issue Description

For the final milestone report, I need to create an extensive scenario that encompasses all core functionalities of our project

### Deadline of the Issue

29 December 2023 - Friday - 10pm

### Reviewer

@elifkizilky 

### Deadline for the Review

29 December 2023 - Friday - 10pm

**Comment by haticerk** [comment]
I have written the scenario. Please review it.

**Comment by elifkizilky** [comment]
It is done and thank you.
