### ISSUE TITLE
Team, Audience Reflections Report

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#883]
### Issue Description

I will write about in project report:
- What we changed and their impact.
- What we can have changed.
- What we learned.
- The reflections of audience in final demo.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

29.12.2023 - Friday - 18.00

### Reviewer

@haticerk 

### Deadline for the Review

29.12.2023 - Friday - 21.00

**Comment by haticerk** [comment]
Well done, I read your part. Thank you!
