### ISSUE TITLE
Individual Contribution Report

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#885]
### Issue Description

I will prepare contribution report for myself.

### Tasks

Parts of the task:
- [ ] ...(1)
- [ ] ...(2)
- [ ] ...(3)

### Deadline of the Issue

29.12.2023 - Friday - 18.00

### Reviewer

@senaal 

### Deadline for the Review

29.12.2023 - Friday - 21.00

**Comment by yunusemrealtug** [comment]
I have written it, needs review.

**Comment by senaal** [comment]
The task is completed, I am closing the issue.
