### ISSUE TITLE
Preparing RAM Draft

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#90]
### Issue Description

For the milestone report, the RAM(responsibility assignment matrix) will be prepared.

### Tasks

Parts of the task:
- [x] Research about RAM
- [x] Preparing RAM Draft

### Final Step

The draft will be filled.

### Deadline of the Issue

07.04.2023

### Reviewer

@frknlke 

### Deadline for the Review

08.04.2023

**Comment by senaal** [comment]
RAM draft is completed, filled and shared with teammates. The issue needs review.

**Comment by frknlke** [comment]
I reviewed the RAM draft. All contributors will edit for each issue that they are mentioned as  a reviewer.  Since there is no error, I am closing the issue.
