### ISSUE TITLE
Milestone Report introduction

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2023group7#93]
### Issue Description

I will do introduction part for our milestone report.

### Tasks

- [x] Milestone Report Introduction

### Deadline of the Issue

08.04.2023

### Reviewer

@yunusemrealtug 

### Deadline for the Review

08.04.2023

**Comment by SouthAscend** [comment]
I don't have enough knowledge to fill out the "References" part.

**Comment by yunusemrealtug** [comment]
I read from pdf. That is relevant. Closed.
