### ISSUE TITLE
Login and Sing Up Page Mock-up for Mobile

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#94]
### Issue Description

We should create login and sing up page mockups for mobile devices

### Tasks

Parts of the task:
- [x]  Analyzing the web mock up
- [x] Creating mock up for mobile

### Deadline of the Issue

09.04.2023

### Reviewer

@elifkizilky 

### Deadline for the Review

09.04.2023

**Comment by tuluyhansozen** [comment]
It is done

**Comment by elifkizilky** [comment]
The work is reviewed and done, thus issue can be closed.
