### ISSUE TITLE
Search Engine Class Diagram

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2023group7#96]
### Issue Description

Class Diagram of the Search Engine

### Deadline of the Issue

08.04.2023

### Reviewer

@elifkizilky 

### Deadline for the Review

08.04.2023

**Comment by elifkizilky** [comment]
The work is completed and can be seen [here](https://github.com/bounswe/bounswe2023group7/wiki/Class-Diagrams) once all the work is uploaded.
