### ISSUE TITLE
Games Page Mock-up

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#97]
### Issue Description

A "Games" page will be added to Mock-ups. So that users can reach to the game profiles in a more fashioned way.

### Deadline of the Issue

09.04.23 17.00

### Reviewer

@tuluyhansozen 

### Deadline for the Review

09.04.23 23.59

**Comment by elifkizilky** [comment]
The page is done and can be seen [here](https://github.com/bounswe/bounswe2023group7/wiki/Mock-Ups) by clicking the figma link.

**Comment by tuluyhansozen** [comment]
I reviewed it
