### ISSUE TITLE
Creating Scenario For Mock Up

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#98]
### Issue Description

Creating realistic scenario for mock up

### Tasks

Parts of the task:
- [x] Scenario 1
- [x] Scenario 2

### Deadline of the Issue

08.04.2023

### Reviewer

@omersafakbebek 

### Deadline for the Review

08.04.2023

**Comment by omersafakbebek** [comment]
The review has been completed. More scenarios will be prepared.
