### ISSUE TITLE
Events Page Mock-up for Mobile 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#99]
### Issue Description

We should create events page mockups for mobile devices

### Tasks

Parts of the task:
- [x] Analyzing the web mock up
- [x] Creating mock up for mobile

### Deadline of the Issue

09.04.2023

### Reviewer

@frknlke 

### Deadline for the Review

09.04.2023

**Comment by tuluyhansozen** [comment]
[Mock Up ](https://www.figma.com/file/ys7rBkkB4wAThXJVYEscff/Design?node-id=0-1&t=UMRgokt9cnguwk5V-0)

**Comment by frknlke** [comment]
I reviewed the mock up. I will close the issue.
